# ─────────────────────────────────────────────────────────────
#  config.py  –  NSE India Focus: Top ~300 stocks + ETFs + MCX
#  Global news feeds → Indian market impact only
# ─────────────────────────────────────────────────────────────
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
)

# ── RSS News Sources (global + Indian) ───────────────────────
NEWS_FEEDS = {
    # ── Indian sources ────────────────────────────────────────
    "Economic Times Markets":    "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
    "Economic Times Stocks":     "https://economictimes.indiatimes.com/markets/stocks/rssfeeds/2146842.cms",
    "Economic Times Companies":  "https://economictimes.indiatimes.com/companies/rssfeeds/2143429.cms",
    "Economic Times Commodities":"https://economictimes.indiatimes.com/markets/commodities/rssfeeds/1957340.cms",
    "Economic Times Economy":    "https://economictimes.indiatimes.com/economy/rssfeeds/1373380680.cms",
    "Moneycontrol Markets":      "https://www.moneycontrol.com/rss/marketreports.xml",
    "Moneycontrol Business":     "https://www.moneycontrol.com/rss/business.xml",
    "Moneycontrol Results":      "https://www.moneycontrol.com/rss/results.xml",
    "Business Standard Markets": "https://www.business-standard.com/rss/markets-106.rss",
    "Business Standard Economy": "https://www.business-standard.com/rss/economy-policy-102.rss",
    "Business Standard Companies":"https://www.business-standard.com/rss/companies-101.rss",
    "Mint Markets":              "https://www.livemint.com/rss/markets",
    "Mint Companies":            "https://www.livemint.com/rss/companies",
    "Mint Money":                "https://www.livemint.com/rss/money",
    "Financial Express Market":  "https://www.financialexpress.com/market/feed/",
    "NDTV Profit":               "https://feeds.feedburner.com/NdtvProfit-LatestNews",
    "Hindu Business Line":       "https://www.thehindubusinessline.com/markets/stock-markets/?service=rss",
    "Zee Business":              "https://zeebiz.com/markets/rss",
    "RBI Press Releases":        "https://www.rbi.org.in/Scripts/rss.aspx",
    "PIB Finance Ministry":      "https://pib.gov.in/RssMain.aspx?ModId=6&Lang=1&Regid=3",
    "PIB Economy":               "https://pib.gov.in/RssMain.aspx?ModId=12&Lang=1&Regid=3",
    # ── Global macro (impact on Indian market) ───────────────
    "Reuters Business":          "https://feeds.reuters.com/reuters/businessNews",
    "Reuters Markets":           "https://feeds.reuters.com/reuters/UKmarkets",
    "CNBC Markets":              "https://www.cnbc.com/id/20910258/device/rss/rss.html",
    "Bloomberg Markets":         "https://feeds.bloomberg.com/markets/news.rss",
    "FT Markets":                "https://www.ft.com/markets?format=rss",
    "Investing.com India":       "https://in.investing.com/rss/news_25.rss",
    # ── Metals / Commodities — Silver, Gold, Crude, Copper ───────
    "Yahoo Finance Silver":      "https://feeds.finance.yahoo.com/rss/2.0/headline?s=SI=F&region=US&lang=en-US",
    "Yahoo Finance Gold":        "https://feeds.finance.yahoo.com/rss/2.0/headline?s=GC=F&region=US&lang=en-US",
    "Yahoo Finance Copper":      "https://feeds.finance.yahoo.com/rss/2.0/headline?s=HG=F&region=US&lang=en-US",
    "Yahoo Finance CrudeOil":    "https://feeds.finance.yahoo.com/rss/2.0/headline?s=CL=F&region=US&lang=en-US",
    "CNBC Commodities":          "https://www.cnbc.com/id/15839135/device/rss/rss.html",
    "Investing.com Commodities": "https://in.investing.com/rss/commodities.rss",
    "Mining.com":                "https://www.mining.com/feed/",
}

# ── Impact Thresholds ─────────────────────────────────────────
IMPACT_THRESHOLDS = {
    "EXTREME": 0.8,
    "HIGH":    0.6,
    "MEDIUM":  0.35,
    "LOW":     0.1,
}

# ── Underreaction Detection Parameters ───────────────────────
UNDERREACTION = {
    "min_expected_move_pct": 3.0,
    "max_actual_move_pct":   1.5,
    "volume_threshold":      1.3,
}

# ── Signal Engine Parameters ──────────────────────────────────
RISK_REWARD_MIN  = 1.5   # relaxed from 2.0 — news trades often have 1.5–2.0 R:R
CONFIDENCE_FLOOR = 50    # relaxed from 55 — allows HIGH impact signals with mixed technicals

# ══════════════════════════════════════════════════════════════
#  NSE INDIA STOCK UNIVERSE
#  Format: "NSE_SYMBOL": {"name": "...", "sector": "...", "keywords": [...]}
#  Yahoo Finance ticker = SYMBOL.NS  (handled in impact_analyzer.py)
#  ETFs / MCX futures listed at bottom
# ══════════════════════════════════════════════════════════════
STOCK_UNIVERSE = {

    # ── BANKING ───────────────────────────────────────────────
    "HDFCBANK":   {"name":"HDFC Bank",            "sector":"Banking", "keywords":["hdfc bank","hdfcbank","hdfc"]},
    "ICICIBANK":  {"name":"ICICI Bank",            "sector":"Banking", "keywords":["icici bank","icicibank","icici"]},
    "SBIN":       {"name":"State Bank of India",   "sector":"Banking", "keywords":["sbi","state bank","sbin","state bank of india"]},
    "KOTAKBANK":  {"name":"Kotak Mahindra Bank",   "sector":"Banking", "keywords":["kotak","kotak bank","kotak mahindra"]},
    "AXISBANK":   {"name":"Axis Bank",             "sector":"Banking", "keywords":["axis bank","axisbank"]},
    "INDUSINDBK": {"name":"IndusInd Bank",         "sector":"Banking", "keywords":["indusind","indusind bank"]},
    "YESBANK":    {"name":"Yes Bank",              "sector":"Banking", "keywords":["yes bank","yesbank"]},
    "IDFCFIRSTB": {"name":"IDFC First Bank",       "sector":"Banking", "keywords":["idfc first","idfcfirstb","idfc bank"]},
    "FEDERALBNK": {"name":"Federal Bank",          "sector":"Banking", "keywords":["federal bank","federalbnk"]},
    "RBLBANK":    {"name":"RBL Bank",              "sector":"Banking", "keywords":["rbl bank","rblbank"]},
    "PNB":        {"name":"Punjab National Bank",  "sector":"Banking", "keywords":["pnb","punjab national bank"]},
    "CANBK":      {"name":"Canara Bank",           "sector":"Banking", "keywords":["canara bank","canbk"]},
    "BANKBARODA": {"name":"Bank of Baroda",        "sector":"Banking", "keywords":["bank of baroda","bankbaroda"]},
    "UNIONBANK":  {"name":"Union Bank of India",   "sector":"Banking", "keywords":["union bank","unionbank"]},
    "IOB":        {"name":"Indian Overseas Bank",  "sector":"Banking", "keywords":["iob","indian overseas bank"]},
    "INDIANB":    {"name":"Indian Bank",           "sector":"Banking", "keywords":["indian bank","indianb"]},
    "UCOBANK":    {"name":"UCO Bank",              "sector":"Banking", "keywords":["uco bank","uco"]},
    "MAHABANK":   {"name":"Bank of Maharashtra",   "sector":"Banking", "keywords":["bank of maharashtra","mahabank"]},
    "KARURVYSYA": {"name":"Karur Vysya Bank",      "sector":"Banking", "keywords":["karur vysya","karurvysya"]},
    "CUB":        {"name":"City Union Bank",       "sector":"Banking", "keywords":["city union bank","cub"]},
    "DCBBANK":    {"name":"DCB Bank",              "sector":"Banking", "keywords":["dcb bank","dcbbank"]},
    "SOUTHBANK":  {"name":"South Indian Bank",     "sector":"Banking", "keywords":["south indian bank","southbank"]},
    "BANDHANBNK": {"name":"Bandhan Bank",          "sector":"Banking", "keywords":["bandhan bank","bandhanbnk"]},
    "AUBANK":     {"name":"AU Small Finance Bank", "sector":"Banking", "keywords":["au small finance","aubank","au bank"]},
    "UJJIVANSFB": {"name":"Ujjivan Small Finance", "sector":"Banking", "keywords":["ujjivan","ujjivansfb"]},
    "EQUITASBNK": {"name":"Equitas Small Finance", "sector":"Banking", "keywords":["equitas","equitasbnk"]},

    # ── NBFC / FINANCE ────────────────────────────────────────
    "BAJFINANCE":  {"name":"Bajaj Finance",         "sector":"NBFC", "keywords":["bajaj finance","bajajfinance"]},
    "BAJAJFINSV":  {"name":"Bajaj Finserv",          "sector":"NBFC", "keywords":["bajaj finserv","bajajfinserv"]},
    "CHOLAFIN":    {"name":"Cholamandalam Finance",  "sector":"NBFC", "keywords":["cholamandalam","cholafin","chola finance"]},
    "MUTHOOTFIN":  {"name":"Muthoot Finance",        "sector":"NBFC", "keywords":["muthoot finance","muthootfin","muthoot"]},
    "MANAPPURAM":  {"name":"Manappuram Finance",     "sector":"NBFC", "keywords":["manappuram","manappuram finance"]},
    "SUNDARMFIN":  {"name":"Sundaram Finance",       "sector":"NBFC", "keywords":["sundaram finance","sundarmfin"]},
    "M&MFIN":      {"name":"M&M Financial Services", "sector":"NBFC", "keywords":["m&m financial","mahindra financial","m&mfin"]},
    "SHRIRAMFIN":  {"name":"Shriram Finance",        "sector":"NBFC", "keywords":["shriram finance","shriramfin"]},
    "POONAWALLA":  {"name":"Poonawalla Fincorp",     "sector":"NBFC", "keywords":["poonawalla fincorp","poonawalla"]},
    "CANFINHOME":  {"name":"Can Fin Homes",          "sector":"NBFC", "keywords":["can fin homes","canfinhome"]},
    "LICHSGFIN":   {"name":"LIC Housing Finance",    "sector":"NBFC", "keywords":["lic housing","lichsgfin"]},
    "PNBHOUSING":  {"name":"PNB Housing Finance",    "sector":"NBFC", "keywords":["pnb housing","pnbhousing"]},
    "HOMEFIRST":   {"name":"Home First Finance",     "sector":"NBFC", "keywords":["home first","homefirst"]},
    "AAVAS":       {"name":"Aavas Financiers",       "sector":"NBFC", "keywords":["aavas","aavas financiers"]},
    "APTUS":       {"name":"Aptus Value Housing",    "sector":"NBFC", "keywords":["aptus","aptus value"]},
    "IBULHSGFIN":  {"name":"Indiabulls Housing",     "sector":"NBFC", "keywords":["indiabulls housing","ibulhsgfin"]},
    "ABCAPITAL":   {"name":"Aditya Birla Capital",   "sector":"NBFC", "keywords":["aditya birla capital","abcapital"]},
    "CREDITACC":   {"name":"CreditAccess Grameen",   "sector":"NBFC", "keywords":["creditaccess","creditacc"]},
    "INDIAMART":   {"name":"IndiaMart InterMesh",    "sector":"NBFC", "keywords":["indiamart","indiamart intermesh"]},

    # ── INSURANCE ─────────────────────────────────────────────
    "HDFCLIFE":   {"name":"HDFC Life Insurance",    "sector":"Insurance", "keywords":["hdfc life","hdfclife"]},
    "SBILIFE":    {"name":"SBI Life Insurance",     "sector":"Insurance", "keywords":["sbi life","sbilife"]},
    "ICICIGI":    {"name":"ICICI Lombard",          "sector":"Insurance", "keywords":["icici lombard","icicigi"]},
    "ICICIPRULI": {"name":"ICICI Prudential Life",  "sector":"Insurance", "keywords":["icici prudential","icicipruli"]},
    "LICI":       {"name":"LIC of India",           "sector":"Insurance", "keywords":["lic","life insurance corporation","lici"]},
    "STARHEALTH": {"name":"Star Health Insurance",  "sector":"Insurance", "keywords":["star health","starhealth"]},
    "MFSL":       {"name":"Max Financial Services", "sector":"Insurance", "keywords":["max financial","mfsl","max life"]},
    "NIACL":      {"name":"New India Assurance",    "sector":"Insurance", "keywords":["new india assurance","niacl"]},
    "GICRE":      {"name":"GIC Re",                 "sector":"Insurance", "keywords":["gic re","gicre","general insurance corp"]},

    # ── WEALTH / BROKING / AMC ────────────────────────────────
    "HDFCAMC":   {"name":"HDFC AMC",            "sector":"AMC/Wealth", "keywords":["hdfc amc","hdfcamc"]},
    "NAM-INDIA": {"name":"Nippon Life India AMC","sector":"AMC/Wealth", "keywords":["nippon amc","nam-india","nippon india mutual"]},
    "ANGELONE":  {"name":"Angel One",           "sector":"AMC/Wealth", "keywords":["angel one","angel-one","angel broking"]},
    "360ONE":    {"name":"360 ONE WAM",         "sector":"AMC/Wealth", "keywords":["360 one","360one"]},
    "CDSL":      {"name":"CDSL",                "sector":"AMC/Wealth", "keywords":["cdsl","central depository services"]},
    "BSE":       {"name":"BSE Ltd",             "sector":"Exchange", "keywords":["bse limited","bse ltd"]},
    "MCX":       {"name":"MCX India",           "sector":"Exchange", "keywords":["mcx","multi commodity exchange","commodity exchange"]},

    # ── IT / TECHNOLOGY ───────────────────────────────────────
    "TCS":        {"name":"TCS",                   "sector":"IT", "keywords":["tcs","tata consultancy","tata consultancy services"]},
    "INFY":       {"name":"Infosys",               "sector":"IT", "keywords":["infosys","infy"]},
    "WIPRO":      {"name":"Wipro",                 "sector":"IT", "keywords":["wipro"]},
    "HCLTECH":    {"name":"HCL Technologies",      "sector":"IT", "keywords":["hcl tech","hcltech","hcl technologies"]},
    "TECHM":      {"name":"Tech Mahindra",         "sector":"IT", "keywords":["tech mahindra","techm"]},
    "LTIM":       {"name":"LTIMindtree",           "sector":"IT", "keywords":["ltimindtree","ltim","mindtree"]},
    "MPHASIS":    {"name":"Mphasis",               "sector":"IT", "keywords":["mphasis"]},
    "PERSISTENT": {"name":"Persistent Systems",    "sector":"IT", "keywords":["persistent","persistent systems"]},
    "COFORGE":    {"name":"Coforge",               "sector":"IT", "keywords":["coforge","niit technologies"]},
    "KPITTECH":   {"name":"KPIT Technologies",     "sector":"IT", "keywords":["kpit","kpit technologies"]},
    "LTTS":       {"name":"L&T Technology Services","sector":"IT","keywords":["ltts","l&t technology services"]},
    "TATAELXSI":  {"name":"Tata Elxsi",            "sector":"IT", "keywords":["tata elxsi","tataelxsi"]},
    "ZENSARTECH": {"name":"Zensar Technologies",   "sector":"IT", "keywords":["zensar","zensartech"]},
    "RAMCOSYS":   {"name":"Ramco Systems",         "sector":"IT", "keywords":["ramco systems"]},
    "BSOFT":      {"name":"BIRLASOFT",             "sector":"IT", "keywords":["birlasoft","bsoft"]},
    "MASTEK":     {"name":"Mastek",                "sector":"IT", "keywords":["mastek"]},
    "HEXT":       {"name":"Hexaware Technologies", "sector":"IT", "keywords":["hexaware","hext"]},
    "NIITLTD":    {"name":"NIIT Ltd",              "sector":"IT", "keywords":["niit"]},
    "RATEGAIN":   {"name":"RateGain Travel Tech",  "sector":"IT", "keywords":["rategain"]},
    "ECLERX":     {"name":"eClerx Services",       "sector":"IT", "keywords":["eclerx"]},
    "FSL":        {"name":"Firstsource Solutions", "sector":"IT", "keywords":["firstsource","fsl"]},
    "NAUKRI":     {"name":"Info Edge (Naukri)",    "sector":"IT", "keywords":["naukri","info edge","infoedge"]},
    "ZOMATO":     {"name":"Zomato",                "sector":"Tech/Consumer","keywords":["zomato"]},
    "PAYTM":      {"name":"Paytm (One97 Comm)",    "sector":"Tech/Consumer","keywords":["paytm","one97"]},
    "NYKAA":      {"name":"Nykaa (FSN E-Commerce)","sector":"Tech/Consumer","keywords":["nykaa","fsn"]},
    "POLICYBZR":  {"name":"PB Fintech (Policybazaar)","sector":"Tech/Consumer","keywords":["policybazaar","policybzr","pb fintech"]},
    "CARTRADE":   {"name":"CarTrade Tech",         "sector":"Tech/Consumer","keywords":["cartrade"]},
    "SWIGGY":     {"name":"Swiggy",                "sector":"Tech/Consumer","keywords":["swiggy"]},
    "IXIGO":      {"name":"ixigo (Le Travenues)",  "sector":"Tech/Consumer","keywords":["ixigo"]},
    "FIRSTCRY":   {"name":"FirstCry",              "sector":"Tech/Consumer","keywords":["firstcry","brainbees"]},
    "MAPMYINDIA": {"name":"MapMyIndia",            "sector":"Tech/Consumer","keywords":["mapmyindia","ce info"]},

    # ── PHARMA / HEALTHCARE ───────────────────────────────────
    "SUNPHARMA":  {"name":"Sun Pharma",            "sector":"Pharma", "keywords":["sun pharma","sunpharma","sun pharmaceutical"]},
    "DRREDDY":    {"name":"Dr. Reddy's Labs",      "sector":"Pharma", "keywords":["dr reddy","drreddy","dr. reddy"]},
    "CIPLA":      {"name":"Cipla",                 "sector":"Pharma", "keywords":["cipla"]},
    "DIVISLAB":   {"name":"Divi's Laboratories",   "sector":"Pharma", "keywords":["divis","divi's","divislab"]},
    "LUPIN":      {"name":"Lupin",                 "sector":"Pharma", "keywords":["lupin"]},
    "TORNTPHARM": {"name":"Torrent Pharma",        "sector":"Pharma", "keywords":["torrent pharma","torntpharm"]},
    "AUROPHARMA": {"name":"Aurobindo Pharma",      "sector":"Pharma", "keywords":["aurobindo","auropharma"]},
    "ALKEM":      {"name":"Alkem Laboratories",    "sector":"Pharma", "keywords":["alkem","alkem laboratories"]},
    "GLENMARK":   {"name":"Glenmark Pharma",       "sector":"Pharma", "keywords":["glenmark"]},
    "ABBOTINDIA": {"name":"Abbott India",          "sector":"Pharma", "keywords":["abbott india","abbotindia"]},
    "NATCOPHARM": {"name":"Natco Pharma",          "sector":"Pharma", "keywords":["natco pharma","natcopharm"]},
    "LALPATHLAB": {"name":"Dr. Lal PathLabs",      "sector":"Pharma", "keywords":["lal pathlab","lalpathlab"]},
    "METROPOLIS": {"name":"Metropolis Healthcare", "sector":"Pharma", "keywords":["metropolis","metropolis healthcare"]},
    "THYROCARE":  {"name":"Thyrocare",             "sector":"Pharma", "keywords":["thyrocare"]},
    "GRANULES":   {"name":"Granules India",        "sector":"Pharma", "keywords":["granules","granules india"]},
    "SYNGENE":    {"name":"Syngene International", "sector":"Pharma", "keywords":["syngene"]},
    "BIOCON":     {"name":"Biocon",                "sector":"Pharma", "keywords":["biocon"]},
    "ZYDUSLIFE":  {"name":"Zydus Lifesciences",    "sector":"Pharma", "keywords":["zydus","cadila","zyduslife"]},
    "WOCKPHARMA": {"name":"Wockhardt",             "sector":"Pharma", "keywords":["wockhardt","wockpharma"]},
    "APOLLOHOSP": {"name":"Apollo Hospitals",      "sector":"Healthcare","keywords":["apollo hospital","apollohosp"]},
    "FORTIS":     {"name":"Fortis Healthcare",     "sector":"Healthcare","keywords":["fortis","fortis healthcare"]},
    "MAXHEALTH":  {"name":"Max Healthcare",        "sector":"Healthcare","keywords":["max healthcare","maxhealth"]},
    "ASTER":      {"name":"Aster DM Healthcare",   "sector":"Healthcare","keywords":["aster","aster dm"]},
    "RAINBOW":    {"name":"Rainbow Children",      "sector":"Healthcare","keywords":["rainbow children","rainbow hospital"]},

    # ── ENERGY / OIL & GAS ───────────────────────────────────
    "RELIANCE":   {"name":"Reliance Industries",   "sector":"Energy", "keywords":["reliance","ril","reliance industries","jio","mukesh ambani"]},
    "ONGC":       {"name":"ONGC",                  "sector":"Oil & Gas","keywords":["ongc","oil and natural gas","oil india"]},
    "BPCL":       {"name":"BPCL",                  "sector":"Oil & Gas","keywords":["bpcl","bharat petroleum"]},
    "IOC":        {"name":"Indian Oil",            "sector":"Oil & Gas","keywords":["ioc","indian oil","indianoil"]},
    "HINDPETRO":  {"name":"HPCL",                  "sector":"Oil & Gas","keywords":["hpcl","hindustan petroleum","hindpetro"]},
    "GAIL":       {"name":"GAIL India",            "sector":"Oil & Gas","keywords":["gail","gail india"]},
    "OIL":        {"name":"Oil India",             "sector":"Oil & Gas","keywords":["oil india","oil india limited"]},
    "PETRONET":   {"name":"Petronet LNG",          "sector":"Oil & Gas","keywords":["petronet","petronet lng"]},
    "CASTROLIND": {"name":"Castrol India",         "sector":"Oil & Gas","keywords":["castrol india","castrolind"]},
    "GSPL":       {"name":"Gujarat State Petronet", "sector":"Oil & Gas","keywords":["gspl","gujarat state petronet"]},
    "IGL":        {"name":"Indraprastha Gas",      "sector":"Oil & Gas","keywords":["igl","indraprastha gas"]},
    "MGL":        {"name":"Mahanagar Gas",         "sector":"Oil & Gas","keywords":["mgl","mahanagar gas"]},
    "GUJTGAS":    {"name":"Gujarat Gas",           "sector":"Oil & Gas","keywords":["gujarat gas","gujtgas"]},
    "ATGL":       {"name":"Adani Total Gas",       "sector":"Oil & Gas","keywords":["adani total gas","atgl"]},

    # ── POWER / UTILITIES ─────────────────────────────────────
    "NTPC":       {"name":"NTPC",                  "sector":"Power","keywords":["ntpc","national thermal power"]},
    "POWERGRID":  {"name":"Power Grid Corp",       "sector":"Power","keywords":["power grid","powergrid"]},
    "ADANIPOWER": {"name":"Adani Power",           "sector":"Power","keywords":["adani power","adanipower"]},
    "TATAPOWER":  {"name":"Tata Power",            "sector":"Power","keywords":["tata power","tatapower"]},
    "TORNTPOWER": {"name":"Torrent Power",         "sector":"Power","keywords":["torrent power","torntpower"]},
    "JSWENERGY":  {"name":"JSW Energy",            "sector":"Power","keywords":["jsw energy","jswenergy"]},
    "NHPC":       {"name":"NHPC",                  "sector":"Power","keywords":["nhpc","national hydro power"]},
    "SJVN":       {"name":"SJVN",                  "sector":"Power","keywords":["sjvn"]},
    "NLCINDIA":   {"name":"NLC India",             "sector":"Power","keywords":["nlc","nlc india"]},
    "CESC":       {"name":"CESC",                  "sector":"Power","keywords":["cesc","calcutta electric"]},
    "RECLTD":     {"name":"REC Limited",           "sector":"Power","keywords":["rec limited","recltd","rural electrification"]},
    "PFC":        {"name":"Power Finance Corp",    "sector":"Power","keywords":["pfc","power finance corp"]},
    "INOXGREEN":  {"name":"INOX Green Energy",     "sector":"Renewables","keywords":["inox green","inoxgreen","inox wind"]},
    "INOXWIND":   {"name":"Inox Wind",             "sector":"Renewables","keywords":["inox wind","inoxwind"]},
    "SUZLON":     {"name":"Suzlon Energy",         "sector":"Renewables","keywords":["suzlon","suzlon energy"]},
    "GREENPANEL": {"name":"Greenpanel Industries",  "sector":"Renewables","keywords":["greenko","greenpanel"]},
    "IREDA":      {"name":"IREDA",                 "sector":"Renewables","keywords":["ireda","indian renewable energy"]},
    "SGBLTD":     {"name":"SGB Ltd",               "sector":"Power","keywords":["sgb"]},  # TODO: verify NSE symbol

    # ── CONGLOMERATES / ADANI GROUP ───────────────────────────
    "ADANIENT":   {"name":"Adani Enterprises",     "sector":"Conglomerate","keywords":["adani enterprises","adanient","gautam adani"]},
    "ADANIPORTS": {"name":"Adani Ports",           "sector":"Infrastructure","keywords":["adani ports","adaniports"]},
    "ADANIGREEN": {"name":"Adani Green Energy",    "sector":"Renewables","keywords":["adani green","adanigreen","adani bravura"]},
    "ADANITRANS": {"name":"Adani Transmission",    "sector":"Power","keywords":["adani transmission","adanitrans"]},
    "AWL":        {"name":"Adani Wilmar",          "sector":"FMCG","keywords":["adani wilmar","awl","fortune oil"]},

    # ── AUTOMOBILE ────────────────────────────────────────────
    "MARUTI":     {"name":"Maruti Suzuki",         "sector":"Automobile","keywords":["maruti","maruti suzuki","suzuki india"]},
    "TATAMOTORS": {"name":"Tata Motors",           "sector":"Automobile","keywords":["tata motors","tatamotors","jaguar","jlr","tata ev"]},
    "M&M":        {"name":"Mahindra & Mahindra",   "sector":"Automobile","keywords":["mahindra","m&m","mahindra mahindra","xuv"]},
    "BAJAJ-AUTO": {"name":"Bajaj Auto",            "sector":"Automobile","keywords":["bajaj auto","bajaj-auto","pulsar"]},
    "HEROMOTOCO": {"name":"Hero MotoCorp",         "sector":"Automobile","keywords":["hero moto","hero motocorp","heromotoco"]},
    "EICHERMOT":  {"name":"Eicher Motors",         "sector":"Automobile","keywords":["eicher","royal enfield","eichermot"]},
    "TVSMOTORS":  {"name":"TVS Motor",             "sector":"Automobile","keywords":["tvs motor","tvsmotors","tvs apache"]},
    "ASHOKLEY":   {"name":"Ashok Leyland",         "sector":"Automobile","keywords":["ashok leyland","ashokley"]},
    "BHARATFORG": {"name":"Bharat Forge",          "sector":"Automobile","keywords":["bharat forge","bharatforg"]},
    "MOTHERSON":  {"name":"Samvardhana Motherson", "sector":"Auto Ancillary","keywords":["motherson","samvardhana motherson"]},
    "BOSCHLTD":   {"name":"Bosch India",           "sector":"Auto Ancillary","keywords":["bosch india","boschltd"]},
    "BALKRISIND": {"name":"Balkrishna Industries", "sector":"Auto Ancillary","keywords":["balkrishna","bkt tyres","balkrisind"]},
    "APOLLOTYRE": {"name":"Apollo Tyres",          "sector":"Auto Ancillary","keywords":["apollo tyres","apollotyre"]},
    "MRF":        {"name":"MRF",                   "sector":"Auto Ancillary","keywords":["mrf","madras rubber"]},
    "CEATLTD":    {"name":"CEAT",                  "sector":"Auto Ancillary","keywords":["ceat","ceatltd"]},
    "EXIDEIND":   {"name":"Exide Industries",      "sector":"Auto Ancillary","keywords":["exide","exideind"]},
    "AMARAJABAT": {"name":"Amara Raja Energy",     "sector":"Auto Ancillary","keywords":["amara raja","amarajabat"]},
    "ESCORTS":    {"name":"Escorts Kubota",        "sector":"Automobile","keywords":["escorts","escorts kubota"]},
    "SONACOMS":   {"name":"Sona BLW Comstar",      "sector":"Auto Ancillary","keywords":["sona blw","sonacoms","sona comstar"]},
    "TIINDIA":    {"name":"Tube Investments",      "sector":"Auto Ancillary","keywords":["tube investments","tiindia"]},
    "AARTISURF":  {"name":"Aarti Surfactants",     "sector":"Auto Ancillary","keywords":["aarti surf"]},
    "OLECTRA":    {"name":"Olectra Greentech",     "sector":"Automobile","keywords":["olectra","ev bus"]},
    "RVNL":       {"name":"RVNL",                  "sector":"Infrastructure","keywords":["rvnl","rail vikas nigam"]},

    # ── METALS / MINING ───────────────────────────────────────
    "TATASTEEL":  {"name":"Tata Steel",            "sector":"Metals","keywords":["tata steel","tatasteel"]},
    "JSWSTEEL":   {"name":"JSW Steel",             "sector":"Metals","keywords":["jsw steel","jswsteel"]},
    "HINDALCO":   {"name":"Hindalco",              "sector":"Metals","keywords":["hindalco","novelis"]},
    "VEDL":       {"name":"Vedanta",               "sector":"Metals","keywords":["vedanta","vedl"]},
    "COALINDIA":  {"name":"Coal India",            "sector":"Mining","keywords":["coal india","coalindia"]},
    "NMDC":       {"name":"NMDC",                  "sector":"Mining","keywords":["nmdc","national mineral"]},
    "SAIL":       {"name":"SAIL",                  "sector":"Metals","keywords":["sail","steel authority"]},
    "NATIONALUM": {"name":"National Aluminium",    "sector":"Metals","keywords":["nalco","national aluminium","nationalum"]},
    "HINDCOPPER": {"name":"Hindustan Copper",      "sector":"Metals","keywords":["hindustan copper","hindcopper"]},
    "MOIL":       {"name":"MOIL",                  "sector":"Mining","keywords":["moil","manganese ore"]},
    "APLAPOLLO":  {"name":"APL Apollo Tubes",      "sector":"Metals","keywords":["apl apollo","aplapollo"]},
    "WELSPUNLIV": {"name":"Welspun Living",        "sector":"Metals","keywords":["welspun","welspunliv"]},
    "RATNAMANI":  {"name":"Ratnamani Metals",      "sector":"Metals","keywords":["ratnamani","ratnamani metals"]},
    "RAMASTEEL":  {"name":"Rama Steel",            "sector":"Metals","keywords":["rama steel"]},
    "SSWL":       {"name":"Steel Strips Wheels",   "sector":"Metals","keywords":["steel strips","sswl"]},

    # ── CEMENT ────────────────────────────────────────────────
    "ULTRACEMCO": {"name":"UltraTech Cement",      "sector":"Cement","keywords":["ultratech cement","ultracemco","ultratech"]},
    "SHREECEM":   {"name":"Shree Cement",          "sector":"Cement","keywords":["shree cement","shreecem"]},
    "AMBUJACEM":  {"name":"Ambuja Cements",        "sector":"Cement","keywords":["ambuja cement","ambujacem"]},
    "ACC":        {"name":"ACC",                   "sector":"Cement","keywords":["acc cement","acc limited"]},
    "DALBHARAT":  {"name":"Dalmia Bharat",         "sector":"Cement","keywords":["dalmia bharat","dalbharat","dalmia cement"]},
    "JKCEMENT":   {"name":"JK Cement",             "sector":"Cement","keywords":["jk cement","jkcement"]},
    "RAMCOCEM":   {"name":"Ramco Cements",         "sector":"Cement","keywords":["ramco cements","ramcocem"]},
    "HEIDELBERG": {"name":"Nuvoco Vistas",         "sector":"Cement","keywords":["heidelberg","nuvoco"]},
    "JKLAKSHMI":  {"name":"JK Lakshmi Cement",     "sector":"Cement","keywords":["jk lakshmi","jklakshmi"]},
    "BIRLACORPN": {"name":"Birla Corporation",     "sector":"Cement","keywords":["birla corporation","birlacorpn"]},
    "STARCEMENT": {"name":"Star Cement",           "sector":"Cement","keywords":["star cement"]},

    # ── FMCG / CONSUMER ───────────────────────────────────────
    "HINDUNILVR": {"name":"Hindustan Unilever",    "sector":"FMCG","keywords":["hul","hindustan unilever","hindunilvr","unilever india"]},
    "ITC":        {"name":"ITC",                   "sector":"FMCG","keywords":["itc"]},
    "NESTLEIND":  {"name":"Nestle India",          "sector":"FMCG","keywords":["nestle","nestleind","nestle india"]},
    "BRITANNIA":  {"name":"Britannia",             "sector":"FMCG","keywords":["britannia"]},
    "DABUR":      {"name":"Dabur India",           "sector":"FMCG","keywords":["dabur"]},
    "MARICO":     {"name":"Marico",                "sector":"FMCG","keywords":["marico","parachute","saffola"]},
    "GODREJCP":   {"name":"Godrej Consumer",       "sector":"FMCG","keywords":["godrej consumer","godrejcp"]},
    "COLPAL":     {"name":"Colgate-Palmolive",     "sector":"FMCG","keywords":["colgate","colpal","colgate palmolive"]},
    "EMAMILTD":   {"name":"Emami",                 "sector":"FMCG","keywords":["emami"]},
    "PGHH":       {"name":"P&G Hygiene",           "sector":"FMCG","keywords":["p&g","procter gamble","pghh"]},
    "GILLETTE":   {"name":"Gillette India",        "sector":"FMCG","keywords":["gillette india"]},
    "HONAUT":     {"name":"Honeywell Automation",  "sector":"FMCG","keywords":["honeywell india","honaut"]},
    "VBL":        {"name":"Varun Beverages",       "sector":"FMCG","keywords":["varun beverages","vbl","pepsi india"]},
    "TASTYBITE":  {"name":"Tasty Bites",           "sector":"FMCG","keywords":["tasty bites"]},
    "VENKEYS":    {"name":"Venky's India",         "sector":"FMCG","keywords":["venky's","venkeys"]},
    "JYOTHYLAB":  {"name":"Jyothy Labs",           "sector":"FMCG","keywords":["jyothy labs","jyothylab"]},
    "TATACONSUM": {"name":"Tata Consumer Products","sector":"FMCG","keywords":["tata consumer","tataconsum","tata tea","tetley"]},
    "UNITDSPR":   {"name":"United Spirits (Diageo)","sector":"FMCG","keywords":["mcdowell","diageo india","united spirits"]},
    "RADICO":     {"name":"Radico Khaitan",        "sector":"FMCG","keywords":["radico khaitan","radico"]},
    "UBL":        {"name":"United Breweries",      "sector":"FMCG","keywords":["united breweries","kingfisher beer","ubl"]},

    # ── INFRASTRUCTURE / DEFENCE ─────────────────────────────
    "LT":         {"name":"Larsen & Toubro",       "sector":"Infrastructure","keywords":["l&t","larsen","larsen and toubro","larsen & toubro"]},
    "LTF":        {"name":"L&T Finance",           "sector":"NBFC","keywords":["l&t finance","ltfh","ltf"]},
    "GMRAIRPORT": {"name":"GMR Airports",          "sector":"Infrastructure","keywords":["gmr","gmr airports","gmrinfra","gmrairport"]},
    "IRCON":      {"name":"IRCON International",   "sector":"Infrastructure","keywords":["ircon","ircon international"]},
    "NBCC":       {"name":"NBCC India",            "sector":"Infrastructure","keywords":["nbcc","national buildings"]},
    "NCC":        {"name":"NCC Limited",           "sector":"Infrastructure","keywords":["ncc limited"]},
    "KNRCON":     {"name":"KNR Constructions",     "sector":"Infrastructure","keywords":["knr","knr constructions"]},
    "PNCINFRA":   {"name":"PNC Infratech",         "sector":"Infrastructure","keywords":["pnc infratech","pncinfra"]},
    "HAL":        {"name":"Hindustan Aeronautics", "sector":"Defence","keywords":["hal","hindustan aeronautics"]},
    "BEL":        {"name":"Bharat Electronics",    "sector":"Defence","keywords":["bel","bharat electronics"]},
    "BHEL":       {"name":"BHEL",                  "sector":"Infrastructure","keywords":["bhel","bharat heavy electricals"]},
    "BEML":       {"name":"BEML",                  "sector":"Defence","keywords":["beml","bharat earth movers"]},
    "COCHINSHIP": {"name":"Cochin Shipyard",       "sector":"Defence","keywords":["cochin shipyard","cochinship"]},
    "MAZDOCK":    {"name":"Mazagon Dock",           "sector":"Defence","keywords":["mazagon dock","mazagondock"]},
    "GRSE":       {"name":"Garden Reach Shipbuilders","sector":"Defence","keywords":["grse","garden reach","garden reach shipbuilders"]},
    "PARAS":      {"name":"Paras Defence",         "sector":"Defence","keywords":["paras defence"]},
    "DCM":        {"name":"DCM Shriram",           "sector":"Infrastructure","keywords":["dcm shriram"]},
    "ABB":        {"name":"ABB India",             "sector":"Infrastructure","keywords":["abb india"]},
    "SIEMENS":    {"name":"Siemens India",         "sector":"Infrastructure","keywords":["siemens india","siemens"]},
    "CUMMINSIND": {"name":"Cummins India",         "sector":"Infrastructure","keywords":["cummins india","cumminsind"]},
    "THERMAX":    {"name":"Thermax",               "sector":"Infrastructure","keywords":["thermax"]},
    "CONCOR":     {"name":"Container Corp",        "sector":"Infrastructure","keywords":["concor","container corporation"]},
    "IRCTC":      {"name":"IRCTC",                 "sector":"Infrastructure","keywords":["irctc","indian railway catering"]},
    "IRFC":       {"name":"IRFC",                  "sector":"Infrastructure","keywords":["irfc","indian railway finance"]},

    # ── REAL ESTATE ───────────────────────────────────────────
    "DLF":        {"name":"DLF",                   "sector":"Real Estate","keywords":["dlf","dlf limited"]},
    "GODREJPROP": {"name":"Godrej Properties",     "sector":"Real Estate","keywords":["godrej properties","godrejprop"]},
    "PRESTIGE":   {"name":"Prestige Estates",      "sector":"Real Estate","keywords":["prestige estates","prestige"]},
    "OBEROIRLTY": {"name":"Oberoi Realty",         "sector":"Real Estate","keywords":["oberoi realty","oberoirlty"]},
    "SUNTECK":    {"name":"Sunteck Realty",        "sector":"Real Estate","keywords":["sunteck","sunteck realty"]},
    "SOBHA":      {"name":"Sobha",                 "sector":"Real Estate","keywords":["sobha","sobha limited"]},
    "BRIGADE":    {"name":"Brigade Enterprises",   "sector":"Real Estate","keywords":["brigade","brigade enterprises"]},
    "LODHA":      {"name":"Macrotech (Lodha)",      "sector":"Real Estate","keywords":["lodha","macrotech","mldnrealty"]},
    "PHOENIXLTD": {"name":"Phoenix Mills",         "sector":"Real Estate","keywords":["phoenix mills","phoenixltd"]},
    "MAHLIFE":    {"name":"Mahindra Lifespace",    "sector":"Real Estate","keywords":["mahindra lifespace","mahlife"]},

    # ── TELECOM ───────────────────────────────────────────────
    "BHARTIARTL": {"name":"Bharti Airtel",         "sector":"Telecom","keywords":["airtel","bharti airtel","bhartiartl"]},
    "IDEA":       {"name":"Vodafone Idea",         "sector":"Telecom","keywords":["vodafone idea","vi telecom","idea cellular"]},
    "TATACOMM":   {"name":"Tata Communications",   "sector":"Telecom","keywords":["tata communications","tatacomm"]},
    "INDUSTOWER": {"name":"Indus Towers",          "sector":"Telecom","keywords":["indus towers","industower","bharti infratel"]},
    "HFCL":       {"name":"HFCL",                  "sector":"Telecom","keywords":["hfcl","himachal futuristic"]},

    # ── CHEMICALS / SPECIALTY ─────────────────────────────────
    "PIDILITIND": {"name":"Pidilite Industries",   "sector":"Chemicals","keywords":["pidilite","fevicol","pidilitind"]},
    "SRF":        {"name":"SRF",                   "sector":"Chemicals","keywords":["srf","srf limited"]},
    "UPL":        {"name":"UPL",                   "sector":"Chemicals","keywords":["upl","united phosphorus"]},
    "DEEPAKNTR":  {"name":"Deepak Nitrite",        "sector":"Chemicals","keywords":["deepak nitrite","deepakntr"]},
    "NAVINFLUOR": {"name":"Navin Fluorine",        "sector":"Chemicals","keywords":["navin fluorine","navinfluor"]},
    "ATUL":       {"name":"Atul Ltd",              "sector":"Chemicals","keywords":["atul","atul limited"]},
    "AARTIIND":   {"name":"Aarti Industries",      "sector":"Chemicals","keywords":["aarti industries","aartiind"]},
    "TATACHEM":   {"name":"Tata Chemicals",        "sector":"Chemicals","keywords":["tata chemicals","tatachem"]},
    "COROMANDEL": {"name":"Coromandel International","sector":"Chemicals","keywords":["coromandel","coromandel international"]},
    "CHAMBLFERT": {"name":"Chambal Fertilisers",   "sector":"Chemicals","keywords":["chambal fertilisers","chamblfert"]},
    "GNFC":       {"name":"GNFC",                  "sector":"Chemicals","keywords":["gnfc","gujarat narmada"]},
    "LINDEINDIA": {"name":"Linde India",           "sector":"Chemicals","keywords":["linde india","lindeindia"]},
    "NOCIL":      {"name":"NOCIL",                 "sector":"Chemicals","keywords":["nocil"]},
    "VINDHYATEL": {"name":"Vindhya Telelinks",     "sector":"Chemicals","keywords":["vindhya telelinks"]},

    # ── CAPITAL GOODS / ENGINEERING ───────────────────────────
    "POLYCAB":    {"name":"Polycab India",         "sector":"Capital Goods","keywords":["polycab","polycab india"]},
    "HAVELLS":    {"name":"Havells India",         "sector":"Capital Goods","keywords":["havells","havells india"]},
    "KEI":        {"name":"KEI Industries",        "sector":"Capital Goods","keywords":["kei","kei industries"]},
    "FINOLEX":    {"name":"Finolex Cables",        "sector":"Capital Goods","keywords":["finolex cables","finolex"]},
    "AIAENG":     {"name":"AIA Engineering",       "sector":"Capital Goods","keywords":["aia engineering","aiaeng"]},
    "ELGIEQUIP":  {"name":"Elgi Equipments",       "sector":"Capital Goods","keywords":["elgi","elgi equipments"]},
    "TIMKEN":     {"name":"Timken India",          "sector":"Capital Goods","keywords":["timken","timken india"]},
    "SKFINDIA":   {"name":"SKF India",             "sector":"Capital Goods","keywords":["skf india","skfindia"]},
    "SCHAEFFLER": {"name":"Schaeffler India",      "sector":"Capital Goods","keywords":["schaeffler india","schaeffler"]},
    "DIXON":      {"name":"Dixon Technologies",    "sector":"Capital Goods","keywords":["dixon","dixon technologies"]},
    "KAYNES":     {"name":"Kaynes Technology",     "sector":"Capital Goods","keywords":["kaynes","kaynes technology"]},
    "SYRMA":      {"name":"Syrma SGS Technology",  "sector":"Capital Goods","keywords":["syrma","syrma sgs"]},
    "HBLPOWER":   {"name":"HBL Power Systems",     "sector":"Capital Goods","keywords":["hbl power","hblpower"]},
    "CGPOWER":    {"name":"CG Power",              "sector":"Capital Goods","keywords":["cg power","cgpower","crompton greaves power"]},
    "VOLTAMP":    {"name":"Voltamp Transformers",  "sector":"Capital Goods","keywords":["voltamp","voltamp transformers"]},

    # ── CONSUMER DURABLES / RETAIL ───────────────────────────
    "TITAN":      {"name":"Titan Company",         "sector":"Consumer","keywords":["titan","tanishq","titan watch"]},
    "DMART":      {"name":"Avenue Supermarts (DMart)","sector":"Retail","keywords":["dmart","avenue supermarts","d-mart"]},
    "TRENT":      {"name":"Trent (Westside)",      "sector":"Retail","keywords":["trent","westside","zudio"]},
    "SHOPERSTOP": {"name":"Shopper's Stop",        "sector":"Retail","keywords":["shoppers stop","shoperstop"]},
    "ABFRL":      {"name":"Aditya Birla Fashion",  "sector":"Retail","keywords":["abfrl","aditya birla fashion","pantaloons"]},
    "VEDANT":     {"name":"Vedant Fashions (Manyavar)","sector":"Retail","keywords":["manyavar","vedant fashions","vedant"]},
    "PAGEIND":    {"name":"Page Industries (Jockey)","sector":"Consumer","keywords":["page industries","jockey india","pageind"]},
    "VMART":      {"name":"V-Mart Retail",         "sector":"Retail","keywords":["v-mart","vmart"]},
    # NYKAA already defined in Tech/Consumer section — not duplicated here
    "RELAXO":     {"name":"Relaxo Footwears",      "sector":"Consumer","keywords":["relaxo","relaxo footwears"]},
    "BATAINDIA":  {"name":"Bata India",            "sector":"Consumer","keywords":["bata india","bataindia"]},
    "VGUARD":     {"name":"V-Guard Industries",    "sector":"Consumer","keywords":["v-guard","vguard"]},
    "VOLTAS":     {"name":"Voltas",                "sector":"Consumer","keywords":["voltas","tata voltas"]},
    "BLUESTARCO": {"name":"Blue Star",             "sector":"Consumer","keywords":["blue star","bluestar"]},
    "WHIRLPOOL":  {"name":"Whirlpool India",       "sector":"Consumer","keywords":["whirlpool india","whirlpool"]},
    "KAJARIACER": {"name":"Kajaria Ceramics",      "sector":"Consumer","keywords":["kajaria ceramics","kajariacer"]},
    "ASIANPAINT": {"name":"Asian Paints",          "sector":"Consumer","keywords":["asian paints","asianpaint"]},
    "BERGEPAINT": {"name":"Berger Paints",         "sector":"Consumer","keywords":["berger paints","bergepaint"]},
    "AKZOINDIA":  {"name":"AkzoNobel India",       "sector":"Consumer","keywords":["akzonobel","akzoindia","dulux"]},
    "KANSAINER":  {"name":"Kansai Nerolac",        "sector":"Consumer","keywords":["kansai nerolac","kansainer","nerolac"]},

    # ── MEDIA / ENTERTAINMENT ────────────────────────────────
    "PVRINOX":    {"name":"PVR INOX",              "sector":"Media","keywords":["pvr","inox","pvrinox","pvr inox","multiplex"]},
    "SUNTV":      {"name":"Sun TV Network",        "sector":"Media","keywords":["sun tv","suntv","sun television"]},
    "ZEEL":       {"name":"Zee Entertainment",     "sector":"Media","keywords":["zee entertainment","zeel","zee tv"]},
    "NETWORK18":  {"name":"Network18 Media",       "sector":"Media","keywords":["network18","cnntv18","colors tv"]},
    "SAREGAMA":   {"name":"Saregama India",        "sector":"Media","keywords":["saregama","hmv"]},
    "NAZARA":     {"name":"Nazara Technologies",   "sector":"Media","keywords":["nazara","nazara technologies","gaming india"]},

    # ── LOGISTICS / AVIATION ─────────────────────────────────
    "INDIGO":     {"name":"IndiGo (InterGlobe)",   "sector":"Aviation","keywords":["air india","airindia","vistara","indigo","interglobe","indigo airlines"]},
    "BLUEDART":   {"name":"Blue Dart Express",     "sector":"Logistics","keywords":["blue dart","bluedart"]},
    "DELHIVERY":  {"name":"Delhivery",             "sector":"Logistics","keywords":["delhivery"]},
    "MAHINDCIE":  {"name":"Mahindra CIE",          "sector":"Auto Ancillary","keywords":["mahindra cie"]},
    "GOKEX":      {"name":"Gokaldas Exports",      "sector":"Logistics","keywords":["gokaldas"]},

    # ── HOSPITALITY / HOTELS ─────────────────────────────────
    "INDHOTEL":   {"name":"Indian Hotels (Taj)",   "sector":"Hospitality","keywords":["indian hotels","taj hotels","indhotel","tata hotels"]},
    "EIHOTEL":    {"name":"EIH (Oberoi Hotels)",   "sector":"Hospitality","keywords":["eih","oberoi hotels","eihotel"]},
    "LEMONTREEL": {"name":"Lemon Tree Hotels",     "sector":"Hospitality","keywords":["lemon tree","lemontreel"]},
    "MHRIL":      {"name":"Mahindra Holidays",     "sector":"Hospitality","keywords":["mahindra holidays","mhril","club mahindra"]},

    # ── EDUCATION ─────────────────────────────────────────────
    "CAREERPOINT":{"name":"Career Point",          "sector":"Education","keywords":["career point"]},
    "MTARTECH":   {"name":"MTAR Technologies",     "sector":"Capital Goods","keywords":["mtar","mtar technologies"]},
    "TEAMLEASE":  {"name":"TeamLease Services",    "sector":"Education","keywords":["teamlease","team lease"]},

    # ── ETFs (NSE-listed) ─────────────────────────────────────
    "GOLDBEES":   {"name":"GoldBees ETF",          "sector":"ETF/Gold","keywords":["goldbees","gold etf","nifty gold","gold bees","nippon gold etf"]},
    "SILVERBEES": {"name":"SilverBees ETF",        "sector":"ETF/Silver","keywords":["silverbees","silver etf","silver bees","nippon silver etf"]},
    "NIFTYBEES":  {"name":"NiftyBees ETF",         "sector":"ETF/Index","keywords":["niftybees","nifty bees","nifty etf","nifty 50 etf"]},
    "BANKBEES":   {"name":"BankBees ETF",          "sector":"ETF/Banking","keywords":["bankbees","bank bees","banking etf","nifty bank etf"]},
    "ITBEES":     {"name":"ITBees ETF",            "sector":"ETF/IT","keywords":["itbees","it bees","it etf","nifty it etf"]},
    "PSUBNKBEES": {"name":"PSU Bank BeES ETF",     "sector":"ETF/Banking","keywords":["psu bank bees","psubank etf"]},
    "PHARMABEES": {"name":"Pharma BeES ETF",       "sector":"ETF/Pharma","keywords":["pharma bees","pharma etf"]},
    "MOM100":     {"name":"Nifty Momentum 100 ETF","sector":"ETF/Index","keywords":["momentum etf","nifty momentum"]},
    "SETFNIF50":  {"name":"SBI Nifty 50 ETF",      "sector":"ETF/Index","keywords":["sbi nifty etf","setfnif50"]},

    # ── MCX COMMODITIES / FUTURES (tracked via commodity indices) ──
    "SILVERMIC":  {"name":"Silver Micro (MCX)",    "sector":"MCX/Silver","keywords":[
                      "silver mcx","silvermic","mcx silver","silver micro","silver mini","silver futures","comex silver",
                      "silver price","spot silver","silver rally","silver slips","silver rises","silver falls",
                      "silver demand","silver supply","silver output","silver production","silver import",
                      "silver etf","silverbees","lbma silver","silver fixing","silver ounce",
                      "precious metals","bullion market","safe haven metal",
                      "industrial silver","solar silver","ev silver","photovoltaic silver",
                      "silver tariff","silver duty","silver india","import duty silver",
                      "si=f","silver coin","silver bar",
                  ]},
    "GOLDM":      {"name":"Gold Mini (MCX)",       "sector":"MCX/Gold","keywords":[
                      "gold mcx","goldm","mcx gold","gold mini","gold futures","comex gold",
                      "gold price","spot gold","gold rally","gold slips","gold rises","gold falls",
                      "gold demand","gold import","gold etf","goldbees","lbma gold","gold fixing",
                      "bullion","safe haven","gold reserve","rbi gold","central bank gold",
                      "gold tariff","gold duty","gc=f","gold ounce","gold bar","gold coin",
                  ]},
    "CRUDEOIL":   {"name":"Crude Oil (MCX)",       "sector":"MCX/Energy","keywords":["crude oil mcx","crude futures","brent crude","wti crude","crude oil price"]},
    "NATURALGAS": {"name":"Natural Gas (MCX)",     "sector":"MCX/Energy","keywords":["natural gas mcx","natgas","natural gas price","ng futures"]},
    "COPPER":     {"name":"Copper (MCX)",          "sector":"MCX/Metal","keywords":["copper mcx","copper futures","mcx copper","comex copper"]},
    "ZINC":       {"name":"Zinc (MCX)",            "sector":"MCX/Metal","keywords":["zinc mcx","zinc futures","mcx zinc"]},
    "LEAD":       {"name":"Lead (MCX)",            "sector":"MCX/Metal","keywords":["lead mcx","lead futures","mcx lead"]},
    "ALUMINIUM":  {"name":"Aluminium (MCX)",       "sector":"MCX/Metal","keywords":["aluminium mcx","aluminum futures","mcx aluminium"]},
    "NICKEL":     {"name":"Nickel (MCX)",          "sector":"MCX/Metal","keywords":["nickel mcx","nickel futures","mcx nickel"]},
}

# ── Sector → Stocks mapping (auto-built) ──────────────────────
SECTOR_STOCKS: dict[str, list[str]] = {}
for _sym, _meta in STOCK_UNIVERSE.items():
    _sec = _meta["sector"]
    SECTOR_STOCKS.setdefault(_sec, []).append(_sym)

# ── Macro Keywords → Sector Impact Map ────────────────────────
MACRO_SECTOR_MAP = {
    "interest rate":   ["Banking","NBFC","Real Estate","Insurance"],
    "repo rate":       ["Banking","NBFC","Real Estate"],
    "inflation":       ["FMCG","Banking","Automobile","Chemicals"],
    "crude oil":       ["Oil & Gas","Automobile","Airlines","Chemicals","MCX/Energy"],
    "oil price":       ["Oil & Gas","MCX/Energy","Automobile"],
    "rupee":           ["IT","Pharma","Oil & Gas"],
    "dollar":          ["IT","Pharma","Oil & Gas","FMCG"],
    "rbi":             ["Banking","NBFC","Insurance","Real Estate"],
    "sebi":            ["Banking","NBFC","AMC/Wealth"],
    "gdp":             ["Banking","Infrastructure","Automobile"],
    "iip":             ["Metals","Infrastructure","Power"],
    "fii":             ["Banking","IT","Metals"],
    "dii":             ["Banking","IT","FMCG"],
    "us fed":          ["IT","Banking","Metals","MCX/Gold","MCX/Silver"],
    "federal reserve": ["IT","Banking","MCX/Gold","MCX/Silver"],
    "china":           ["Metals","Pharma","Chemicals","MCX/Metal"],
    "monsoon":         ["FMCG","Chemicals","Automobile"],
    "budget":          ["Banking","Infrastructure","FMCG","Automobile","Defence"],
    "gst":             ["FMCG","Automobile","Real Estate"],
    "semiconductor":   ["IT","Capital Goods","Automobile"],
    "ai":              ["IT","Capital Goods"],
    "tariff":          ["Metals","IT","Automobile","Pharma","Chemicals"],
    "gold price":      ["ETF/Gold","MCX/Gold","FMCG"],
    "silver price":    ["ETF/Silver","MCX/Silver","Metals"],
    "gold":            ["ETF/Gold","MCX/Gold"],
    "silver":          ["ETF/Silver","MCX/Silver"],
    "bullion":         ["ETF/Gold","ETF/Silver","MCX/Gold","MCX/Silver"],
    "precious metal":  ["ETF/Gold","ETF/Silver","MCX/Gold","MCX/Silver","Metals"],
    "safe haven":      ["ETF/Gold","MCX/Gold","ETF/Silver","MCX/Silver"],
    "comex":           ["MCX/Silver","MCX/Gold","MCX/Metal"],
    "lbma":            ["MCX/Gold","MCX/Silver"],
    "commodity":       ["MCX/Energy","MCX/Metal","Metals","Oil & Gas"],
    "defence":         ["Defence"],
    "railway":         ["Infrastructure","Capital Goods"],
    "infrastructure":  ["Infrastructure","Capital Goods","Cement"],
    "real estate":     ["Real Estate","Cement","Banking"],
    "renewable":       ["Renewables","Power"],
    "solar":           ["Renewables","Power","Capital Goods"],
    "ev":              ["Automobile","Auto Ancillary","MCX/Metal"],
    "electric vehicle":["Automobile","Auto Ancillary"],
    "pharma":          ["Pharma","Healthcare"],
    "fda":             ["Pharma"],
    "earning":         [],  # handled per-stock
}

# ── Category Detection Keywords ───────────────────────────────
CATEGORY_KEYWORDS = {
    "Earnings":    ["q1","q2","q3","q4","quarterly","results","profit","revenue","earnings","net profit","ebitda","pat","eps"],
    "Macro":       ["rbi","fed","gdp","inflation","repo rate","interest rate","cpi","iip","fiscal","monetary policy","budget"],
    "Geopolitical":["war","conflict","sanction","tension","geopolitical","ukraine","russia","china","taiwan","middle east","iran","us-india"],
    "Sector":      ["sector","industry","auto sales","pmi","capacity","output","production"],
    "Company":     ["acquisition","merger","buyback","dividend","deal","contract","order","launch","ipo","stake","joint venture","jv"],
    "Regulatory":  ["sebi","cci","penalty","fine","nclat","court","regulatory","ban","approval","licence","usfda","who","fda"],
    "Commodity":   ["gold","silver","crude","oil","copper","zinc","aluminium","nickel","mcx","comex","commodity",
                    "bullion","precious metal","spot gold","spot silver","safe haven","lbma","kitco",
                    "silver price","gold price","silver futures","gold futures","industrial metal",
                    "photovoltaic","solar panel","ev battery","base metal"],
}

# ── Historical Reaction Patterns ─────────────────────────────
HISTORICAL_REACTIONS = {
    ("Earnings",    "Positive", "EXTREME"): +8.0,
    ("Earnings",    "Positive", "HIGH"):    +6.5,
    ("Earnings",    "Positive", "MEDIUM"):  +3.2,
    ("Earnings",    "Negative", "EXTREME"): -9.0,
    ("Earnings",    "Negative", "HIGH"):    -7.0,
    ("Earnings",    "Negative", "MEDIUM"):  -3.5,
    ("Macro",       "Positive", "HIGH"):    +2.5,
    ("Macro",       "Negative", "HIGH"):    -2.8,
    ("Company",     "Positive", "EXTREME"): +7.0,
    ("Company",     "Positive", "HIGH"):    +5.0,
    ("Company",     "Negative", "HIGH"):    -5.5,
    ("Regulatory",  "Negative", "HIGH"):    -4.5,
    ("Regulatory",  "Positive", "HIGH"):    +3.0,
    ("Geopolitical","Negative", "EXTREME"): -3.5,
    ("Sector",      "Positive", "MEDIUM"):  +2.0,
    ("Commodity",   "Positive", "HIGH"):    +4.0,
    ("Commodity",   "Negative", "HIGH"):    -4.0,
    # ── Extended coverage (reduce fallback to score × 5.0) ──
    ("Earnings",    "Positive", "LOW"):     +1.5,
    ("Earnings",    "Negative", "LOW"):     -1.5,
    ("Macro",       "Positive", "EXTREME"): +4.0,
    ("Macro",       "Positive", "MEDIUM"):  +1.5,
    ("Macro",       "Negative", "EXTREME"): -4.5,
    ("Macro",       "Negative", "MEDIUM"):  -1.8,
    ("Company",     "Positive", "MEDIUM"):  +2.5,
    ("Company",     "Negative", "EXTREME"): -8.0,
    ("Company",     "Negative", "MEDIUM"):  -3.0,
    ("Regulatory",  "Positive", "MEDIUM"):  +1.5,
    ("Regulatory",  "Negative", "EXTREME"): -6.0,
    ("Regulatory",  "Negative", "MEDIUM"):  -2.5,
    ("Geopolitical","Negative", "HIGH"):    -2.5,
    ("Geopolitical","Positive", "HIGH"):    +1.5,
    ("Sector",      "Positive", "HIGH"):    +3.0,
    ("Sector",      "Negative", "HIGH"):    -2.5,
    ("Sector",      "Negative", "MEDIUM"):  -1.5,
    ("Commodity",   "Positive", "EXTREME"): +6.0,
    ("Commodity",   "Negative", "EXTREME"): -6.0,
    ("Commodity",   "Positive", "MEDIUM"):  +2.0,
    ("Commodity",   "Negative", "MEDIUM"):  -2.0,
}
