# ─────────────────────────────────────────────────────────────
# nifty500.py — auto-generated NSE Nifty 500 universe.
# Source: NSE ind_nifty500list.csv. Merged into config.STOCK_UNIVERSE;
# existing curated entries take precedence (this only ADDS new symbols).
# ─────────────────────────────────────────────────────────────
NIFTY500 = {
    '360ONE': {"name": '360 ONE WAM', "sector": 'Financial Services', "keywords": ['360 one wam', '360one']},
    '3MINDIA': {"name": '3M India', "sector": 'Diversified', "keywords": ['3m india', '3mindia']},
    'AADHARHFC': {"name": 'Aadhar Housing Finance', "sector": 'NBFC', "keywords": ['aadhar housing finance', 'aadharhfc']},
    'AARTIIND': {"name": 'Aarti Industries', "sector": 'Chemicals', "keywords": ['aarti industries', 'aartiind']},
    'AAVAS': {"name": 'Aavas Financiers', "sector": 'Financial Services', "keywords": ['aavas', 'aavas financiers']},
    'ABB': {"name": 'ABB India', "sector": 'Capital Goods', "keywords": ['abb', 'abb india']},
    'ABBOTINDIA': {"name": 'Abbott India', "sector": 'Pharma', "keywords": ['abbotindia', 'abbott india']},
    'ABCAPITAL': {"name": 'Aditya Birla Capital', "sector": 'NBFC', "keywords": ['abcapital', 'aditya birla capital']},
    'ABDL': {"name": 'Allied Blenders and Distillers', "sector": 'FMCG', "keywords": ['abdl', 'allied blenders and distillers']},
    'ABFRL': {"name": 'Aditya Birla Fashion and Retail', "sector": 'Consumer', "keywords": ['abfrl', 'aditya birla fashion and retail']},
    'ABLBL': {"name": 'Aditya Birla Lifestyle Brands', "sector": 'Consumer', "keywords": ['ablbl', 'aditya birla lifestyle brands']},
    'ABREL': {"name": 'Aditya Birla Real Estate', "sector": 'Real Estate', "keywords": ['abrel', 'aditya birla real estate']},
    'ABSLAMC': {"name": 'Aditya Birla Sun Life AMC', "sector": 'Insurance', "keywords": ['abslamc', 'aditya birla sun life amc']},
    'ACC': {"name": 'ACC', "sector": 'Cement', "keywords": ['acc']},
    'ACE': {"name": 'Action Construction Equipment', "sector": 'Capital Goods', "keywords": ['ace', 'action construction equipment']},
    'ACMESOLAR': {"name": 'ACME Solar Holdings', "sector": 'Power', "keywords": ['acme solar holdings', 'acmesolar']},
    'ACUTAAS': {"name": 'Acutaas Chemicals', "sector": 'Pharma', "keywords": ['acutaas', 'acutaas chemicals']},
    'ADANIENSOL': {"name": 'Adani Energy Solutions', "sector": 'Power', "keywords": ['adani energy solutions', 'adaniensol']},
    'ADANIENT': {"name": 'Adani Enterprises', "sector": 'Metals', "keywords": ['adani enterprises', 'adanient']},
    'ADANIGREEN': {"name": 'Adani Green Energy', "sector": 'Power', "keywords": ['adani green energy', 'adanigreen']},
    'ADANIPORTS': {"name": 'Adani Ports and Special Economic Zone', "sector": 'Services', "keywords": ['adani ports and special economic zone', 'adaniports']},
    'ADANIPOWER': {"name": 'Adani Power', "sector": 'Power', "keywords": ['adani power', 'adanipower']},
    'AEGISLOG': {"name": 'Aegis Logistics', "sector": 'Oil & Gas', "keywords": ['aegis logistics', 'aegislog']},
    'AEGISVOPAK': {"name": 'Aegis Vopak Terminals', "sector": 'Oil & Gas', "keywords": ['aegis vopak terminals', 'aegisvopak']},
    'AFCONS': {"name": 'Afcons Infrastructure', "sector": 'Infrastructure', "keywords": ['afcons', 'afcons infrastructure']},
    'AFFLE': {"name": 'Affle 3i', "sector": 'IT', "keywords": ['affle', 'affle 3i']},
    'AIAENG': {"name": 'AIA Engineering', "sector": 'Capital Goods', "keywords": ['aia engineering', 'aiaeng']},
    'AIIL': {"name": 'Authum Investment & Infrastructure', "sector": 'NBFC', "keywords": ['aiil', 'authum investment & infrastructure']},
    'AJANTPHARM': {"name": 'Ajanta Pharmaceuticals', "sector": 'Pharma', "keywords": ['ajanta pharmaceuticals', 'ajantpharm']},
    'ALKEM': {"name": 'Alkem Laboratories', "sector": 'Pharma', "keywords": ['alkem', 'alkem laboratories']},
    'AMBER': {"name": 'Amber Enterprises India', "sector": 'Consumer Durables', "keywords": ['amber', 'amber enterprises india']},
    'AMBUJACEM': {"name": 'Ambuja Cements', "sector": 'Cement', "keywords": ['ambuja cements', 'ambujacem']},
    'ANANDRATHI': {"name": 'Anand Rathi Wealth', "sector": 'AMC/Wealth', "keywords": ['anand rathi wealth', 'anandrathi']},
    'ANANTRAJ': {"name": 'Anant Raj', "sector": 'Real Estate', "keywords": ['anant raj', 'anantraj']},
    'ANGELONE': {"name": 'Angel One', "sector": 'Financial Services', "keywords": ['angel one', 'angelone']},
    'ANTHEM': {"name": 'Anthem Biosciences', "sector": 'Pharma', "keywords": ['anthem', 'anthem biosciences']},
    'ANURAS': {"name": 'Anupam Rasayan India', "sector": 'Chemicals', "keywords": ['anupam rasayan india', 'anuras']},
    'APARINDS': {"name": 'Apar Industries', "sector": 'Capital Goods', "keywords": ['apar industries', 'aparinds']},
    'APLAPOLLO': {"name": 'APL Apollo Tubes', "sector": 'Capital Goods', "keywords": ['apl apollo tubes', 'aplapollo']},
    'APOLLOHOSP': {"name": 'Apollo Hospitals Enterprise', "sector": 'Pharma', "keywords": ['apollo hospitals enterprise', 'apollohosp']},
    'APOLLOTYRE': {"name": 'Apollo Tyres', "sector": 'Automobile', "keywords": ['apollo tyres', 'apollotyre']},
    'APTUS': {"name": 'Aptus Value Housing Finance India', "sector": 'NBFC', "keywords": ['aptus', 'aptus value housing finance india']},
    'ARE&M': {"name": 'Amara Raja Energy & Mobility', "sector": 'Automobile', "keywords": ['amara raja energy & mobility', 'are&m']},
    'ASAHIINDIA': {"name": 'Asahi India Glass', "sector": 'Automobile', "keywords": ['asahi india glass', 'asahiindia']},
    'ASHOKLEY': {"name": 'Ashok Leyland', "sector": 'Capital Goods', "keywords": ['ashok leyland', 'ashokley']},
    'ASIANPAINT': {"name": 'Asian Paints', "sector": 'Consumer Durables', "keywords": ['asian paints', 'asianpaint']},
    'ASTERDM': {"name": 'Aster DM Healthcare', "sector": 'Pharma', "keywords": ['aster dm healthcare', 'asterdm']},
    'ASTRAL': {"name": 'Astral', "sector": 'Capital Goods', "keywords": ['astral']},
    'ATGL': {"name": 'Adani Total Gas', "sector": 'Oil & Gas', "keywords": ['adani total gas', 'atgl']},
    'ATHERENERG': {"name": 'Ather Energy', "sector": 'Automobile', "keywords": ['ather energy', 'atherenerg']},
    'ATUL': {"name": 'Atul', "sector": 'Chemicals', "keywords": ['atul']},
    'AUBANK': {"name": 'AU Small Finance Bank', "sector": 'Banking', "keywords": ['au small finance bank', 'aubank']},
    'AUROPHARMA': {"name": 'Aurobindo Pharma', "sector": 'Pharma', "keywords": ['aurobindo pharma', 'auropharma']},
    'AWL': {"name": 'AWL Agri Business', "sector": 'FMCG', "keywords": ['awl', 'awl agri business']},
    'AXISBANK': {"name": 'Axis Bank', "sector": 'Banking', "keywords": ['axis bank', 'axisbank']},
    'BAJAJ-AUTO': {"name": 'Bajaj Auto', "sector": 'Automobile', "keywords": ['bajaj auto', 'bajaj-auto']},
    'BAJAJFINSV': {"name": 'Bajaj Finserv', "sector": 'Financial Services', "keywords": ['bajaj finserv', 'bajajfinsv']},
    'BAJAJHFL': {"name": 'Bajaj Housing Finance', "sector": 'NBFC', "keywords": ['bajaj housing finance', 'bajajhfl']},
    'BAJAJHLDNG': {"name": 'Bajaj Holdings & Investment', "sector": 'NBFC', "keywords": ['bajaj holdings & investment', 'bajajhldng']},
    'BAJFINANCE': {"name": 'Bajaj Finance', "sector": 'NBFC', "keywords": ['bajaj finance', 'bajfinance']},
    'BALKRISIND': {"name": 'Balkrishna Industries', "sector": 'Automobile', "keywords": ['balkrishna industries', 'balkrisind']},
    'BALRAMCHIN': {"name": 'Balrampur Chini Mills', "sector": 'FMCG', "keywords": ['balramchin', 'balrampur chini mills']},
    'BANDHANBNK': {"name": 'Bandhan Bank', "sector": 'Banking', "keywords": ['bandhan bank', 'bandhanbnk']},
    'BANKBARODA': {"name": 'Bank of Baroda', "sector": 'Banking', "keywords": ['bank of baroda', 'bankbaroda']},
    'BANKINDIA': {"name": 'Bank of India', "sector": 'Banking', "keywords": ['bank of india', 'bankindia']},
    'BATAINDIA': {"name": 'Bata India', "sector": 'Consumer Durables', "keywords": ['bata india', 'bataindia']},
    'BAYERCROP': {"name": 'Bayer Cropscience', "sector": 'Chemicals', "keywords": ['bayer cropscience', 'bayercrop']},
    'BBTC': {"name": 'Bombay Burmah Trading', "sector": 'FMCG', "keywords": ['bbtc', 'bombay burmah trading']},
    'BDL': {"name": 'Bharat Dynamics', "sector": 'Capital Goods', "keywords": ['bdl', 'bharat dynamics']},
    'BEL': {"name": 'Bharat Electronics', "sector": 'Capital Goods', "keywords": ['bel', 'bharat electronics']},
    'BELRISE': {"name": 'Belrise Industries', "sector": 'Automobile', "keywords": ['belrise', 'belrise industries']},
    'BEML': {"name": 'BEML', "sector": 'Capital Goods', "keywords": ['beml']},
    'BERGEPAINT': {"name": 'Berger Paints India', "sector": 'Consumer Durables', "keywords": ['bergepaint', 'berger paints india']},
    'BHARATFORG': {"name": 'Bharat Forge', "sector": 'Automobile', "keywords": ['bharat forge', 'bharatforg']},
    'BHARTIARTL': {"name": 'Bharti Airtel', "sector": 'Telecom', "keywords": ['bharti airtel', 'bhartiartl']},
    'BHARTIHEXA': {"name": 'Bharti Hexacom', "sector": 'Telecom', "keywords": ['bharti hexacom', 'bhartihexa']},
    'BHEL': {"name": 'Bharat Heavy Electricals', "sector": 'Capital Goods', "keywords": ['bharat heavy electricals', 'bhel']},
    'BIKAJI': {"name": 'Bikaji Foods International', "sector": 'FMCG', "keywords": ['bikaji', 'bikaji foods international']},
    'BIOCON': {"name": 'Biocon', "sector": 'Pharma', "keywords": ['biocon']},
    'BLS': {"name": 'BLS International Services', "sector": 'Consumer', "keywords": ['bls', 'bls international services']},
    'BLUEDART': {"name": 'Blue Dart Express', "sector": 'Services', "keywords": ['blue dart express', 'bluedart']},
    'BLUEJET': {"name": 'Blue Jet Healthcare', "sector": 'Pharma', "keywords": ['blue jet healthcare', 'bluejet']},
    'BLUESTARCO': {"name": 'Blue Star', "sector": 'Consumer Durables', "keywords": ['blue star', 'bluestarco']},
    'BOSCHLTD': {"name": 'Bosch', "sector": 'Automobile', "keywords": ['bosch', 'boschltd']},
    'BPCL': {"name": 'Bharat Petroleum', "sector": 'Oil & Gas', "keywords": ['bharat petroleum', 'bpcl']},
    'BRIGADE': {"name": 'Brigade Enterprises', "sector": 'Real Estate', "keywords": ['brigade', 'brigade enterprises']},
    'BRITANNIA': {"name": 'Britannia Industries', "sector": 'FMCG', "keywords": ['britannia', 'britannia industries']},
    'BSE': {"name": 'BSE', "sector": 'Financial Services', "keywords": ['bse']},
    'BSOFT': {"name": 'Birlasoft', "sector": 'IT', "keywords": ['birlasoft', 'bsoft']},
    'CAMS': {"name": 'Computer Age Management Services', "sector": 'Financial Services', "keywords": ['cams', 'computer age management services']},
    'CANBK': {"name": 'Canara Bank', "sector": 'Banking', "keywords": ['canara bank', 'canbk']},
    'CANFINHOME': {"name": 'Can Fin Homes', "sector": 'Financial Services', "keywords": ['can fin homes', 'canfinhome']},
    'CANHLIFE': {"name": 'Canara HSBC Life Insurance', "sector": 'Insurance', "keywords": ['canara hsbc life insurance', 'canhlife']},
    'CAPLIPOINT': {"name": 'Caplin Point Laboratories', "sector": 'Pharma', "keywords": ['caplin point laboratories', 'caplipoint']},
    'CARBORUNIV': {"name": 'Carborundum Universal', "sector": 'Capital Goods', "keywords": ['carborundum universal', 'carboruniv']},
    'CARTRADE': {"name": 'Cartrade Tech', "sector": 'Consumer', "keywords": ['cartrade', 'cartrade tech']},
    'CASTROLIND': {"name": 'Castrol India', "sector": 'Oil & Gas', "keywords": ['castrol india', 'castrolind']},
    'CCL': {"name": 'CCL Products', "sector": 'FMCG', "keywords": ['ccl', 'ccl products']},
    'CDSL': {"name": 'Central Depository Services', "sector": 'NBFC', "keywords": ['cdsl', 'central depository services']},
    'CEATLTD': {"name": 'Ceat', "sector": 'Automobile', "keywords": ['ceat', 'ceatltd']},
    'CEMPRO': {"name": 'Cemindia Projects', "sector": 'Infrastructure', "keywords": ['cemindia projects', 'cempro']},
    'CENTRALBK': {"name": 'Central Bank of India', "sector": 'Banking', "keywords": ['central bank of india', 'centralbk']},
    'CESC': {"name": 'CESC', "sector": 'Power', "keywords": ['cesc']},
    'CGCL': {"name": 'Capri Global Capital', "sector": 'NBFC', "keywords": ['capri global capital', 'cgcl']},
    'CGPOWER': {"name": 'CG Power and Industrial Solutions', "sector": 'Capital Goods', "keywords": ['cg power and industrial solutions', 'cgpower']},
    'CHALET': {"name": 'Chalet Hotels', "sector": 'Consumer', "keywords": ['chalet', 'chalet hotels']},
    'CHAMBLFERT': {"name": 'Chambal Fertilizers & Chemicals', "sector": 'Chemicals', "keywords": ['chambal fertilizers & chemicals', 'chamblfert']},
    'CHENNPETRO': {"name": 'Chennai Petroleum', "sector": 'Oil & Gas', "keywords": ['chennai petroleum', 'chennpetro']},
    'CHOICEIN': {"name": 'Choice International', "sector": 'Financial Services', "keywords": ['choice international', 'choicein']},
    'CHOLAFIN': {"name": 'Cholamandalam Investment and Finance', "sector": 'NBFC', "keywords": ['cholafin', 'cholamandalam investment and finance']},
    'CHOLAHLDNG': {"name": 'Cholamandalam Financial Holdings', "sector": 'NBFC', "keywords": ['cholahldng', 'cholamandalam financial holdings']},
    'CIEINDIA': {"name": 'CIE Automotive India', "sector": 'Automobile', "keywords": ['cie automotive india', 'cieindia']},
    'CIPLA': {"name": 'Cipla', "sector": 'Pharma', "keywords": ['cipla']},
    'CLEAN': {"name": 'Clean Science and Technology', "sector": 'Chemicals', "keywords": ['clean', 'clean science and technology']},
    'COALINDIA': {"name": 'Coal India', "sector": 'Oil & Gas', "keywords": ['coal india', 'coalindia']},
    'COCHINSHIP': {"name": 'Cochin Shipyard', "sector": 'Capital Goods', "keywords": ['cochin shipyard', 'cochinship']},
    'COFORGE': {"name": 'Coforge', "sector": 'IT', "keywords": ['coforge']},
    'COHANCE': {"name": 'Cohance Lifesciences', "sector": 'Pharma', "keywords": ['cohance', 'cohance lifesciences']},
    'COLPAL': {"name": 'Colgate Palmolive', "sector": 'FMCG', "keywords": ['colgate palmolive', 'colpal']},
    'CONCOR': {"name": 'Container of India', "sector": 'Services', "keywords": ['concor', 'container of india']},
    'CONCORDBIO': {"name": 'Concord Biotech', "sector": 'Pharma', "keywords": ['concord biotech', 'concordbio']},
    'COROMANDEL': {"name": 'Coromandel International', "sector": 'Chemicals', "keywords": ['coromandel', 'coromandel international']},
    'CPPLUS': {"name": 'Aditya Infotech', "sector": 'Capital Goods', "keywords": ['aditya infotech', 'cpplus']},
    'CRAFTSMAN': {"name": 'Craftsman Automation', "sector": 'Automobile', "keywords": ['craftsman', 'craftsman automation']},
    'CREDITACC': {"name": 'CreditAccess Grameen', "sector": 'Financial Services', "keywords": ['creditacc', 'creditaccess grameen']},
    'CRISIL': {"name": 'CRISIL', "sector": 'Financial Services', "keywords": ['crisil']},
    'CROMPTON': {"name": 'Crompton Greaves Consumer Electricals', "sector": 'Consumer Durables', "keywords": ['crompton', 'crompton greaves consumer electricals']},
    'CUB': {"name": 'City Union Bank', "sector": 'Banking', "keywords": ['city union bank', 'cub']},
    'CUMMINSIND': {"name": 'Cummins India', "sector": 'Capital Goods', "keywords": ['cummins india', 'cumminsind']},
    'CYIENT': {"name": 'Cyient', "sector": 'IT', "keywords": ['cyient']},
    'DABUR': {"name": 'Dabur India', "sector": 'FMCG', "keywords": ['dabur', 'dabur india']},
    'DALBHARAT': {"name": 'Dalmia Bharat', "sector": 'Cement', "keywords": ['dalbharat', 'dalmia bharat']},
    'DATAPATTNS': {"name": 'Data Patterns', "sector": 'Capital Goods', "keywords": ['data patterns', 'datapattns']},
    'DCMSHRIRAM': {"name": 'DCM Shriram', "sector": 'Diversified', "keywords": ['dcm shriram', 'dcmshriram']},
    'DEEPAKFERT': {"name": 'Deepak Fertilisers & Petrochemicals', "sector": 'Chemicals', "keywords": ['deepak fertilisers & petrochemicals', 'deepakfert']},
    'DEEPAKNTR': {"name": 'Deepak Nitrite', "sector": 'Chemicals', "keywords": ['deepak nitrite', 'deepakntr']},
    'DELHIVERY': {"name": 'Delhivery', "sector": 'Services', "keywords": ['delhivery']},
    'DEVYANI': {"name": 'Devyani International', "sector": 'Consumer', "keywords": ['devyani', 'devyani international']},
    'DIVISLAB': {"name": "Divi's Laboratories", "sector": 'Pharma', "keywords": ["divi's laboratories", 'divislab']},
    'DIXON': {"name": 'Dixon Technologies', "sector": 'Consumer Durables', "keywords": ['dixon', 'dixon technologies']},
    'DLF': {"name": 'DLF', "sector": 'Real Estate', "keywords": ['dlf']},
    'DMART': {"name": 'Avenue Supermarts', "sector": 'Consumer', "keywords": ['avenue supermarts', 'dmart']},
    'DOMS': {"name": 'DOMS Industries', "sector": 'FMCG', "keywords": ['doms', 'doms industries']},
    'DRREDDY': {"name": "Dr Reddy's Laboratories", "sector": 'Pharma', "keywords": ["dr reddy's laboratories", 'drreddy']},
    'ECLERX': {"name": 'eClerx Services', "sector": 'Services', "keywords": ['eclerx', 'eclerx services']},
    'EICHERMOT': {"name": 'Eicher Motors', "sector": 'Automobile', "keywords": ['eicher motors', 'eichermot']},
    'EIDPARRY': {"name": 'E I D Parry', "sector": 'FMCG', "keywords": ['e i d parry', 'eidparry']},
    'EIHOTEL': {"name": 'EIH', "sector": 'Consumer', "keywords": ['eihotel']},
    'ELECON': {"name": 'Elecon Engineering', "sector": 'Capital Goods', "keywords": ['elecon', 'elecon engineering']},
    'ELGIEQUIP': {"name": 'Elgi Equipments', "sector": 'Capital Goods', "keywords": ['elgi equipments', 'elgiequip']},
    'EMAMILTD': {"name": 'Emami', "sector": 'FMCG', "keywords": ['emami', 'emamiltd']},
    'EMCURE': {"name": 'Emcure Pharmaceuticals', "sector": 'Pharma', "keywords": ['emcure', 'emcure pharmaceuticals']},
    'EMMVEE': {"name": 'Emmvee Photovoltaic Power', "sector": 'Capital Goods', "keywords": ['emmvee', 'emmvee photovoltaic power']},
    'ENDURANCE': {"name": 'Endurance Technologies', "sector": 'Automobile', "keywords": ['endurance', 'endurance technologies']},
    'ENGINERSIN': {"name": 'Engineers India', "sector": 'Infrastructure', "keywords": ['engineers india', 'enginersin']},
    'ENRIN': {"name": 'Siemens Energy India', "sector": 'Capital Goods', "keywords": ['enrin', 'siemens energy india']},
    'ERIS': {"name": 'Eris Lifesciences', "sector": 'Pharma', "keywords": ['eris', 'eris lifesciences']},
    'ESCORTS': {"name": 'Escorts Kubota', "sector": 'Capital Goods', "keywords": ['escorts', 'escorts kubota']},
    'ETERNAL': {"name": 'Eternal', "sector": 'Consumer', "keywords": ['eternal']},
    'EXIDEIND': {"name": 'Exide Industries', "sector": 'Automobile', "keywords": ['exide industries', 'exideind']},
    'FACT': {"name": 'Fertilisers and Chemicals Travancore', "sector": 'Chemicals', "keywords": ['fact', 'fertilisers and chemicals travancore']},
    'FEDERALBNK': {"name": 'Federal Bank', "sector": 'Banking', "keywords": ['federal bank', 'federalbnk']},
    'FINCABLES': {"name": 'Finolex Cables', "sector": 'Capital Goods', "keywords": ['fincables', 'finolex cables']},
    'FIRSTCRY': {"name": 'Brainbees Solutions', "sector": 'Consumer', "keywords": ['brainbees solutions', 'firstcry']},
    'FIVESTAR': {"name": 'Five-Star Business Finance', "sector": 'NBFC', "keywords": ['five-star business finance', 'fivestar']},
    'FLUOROCHEM': {"name": 'Gujarat Fluorochemicals', "sector": 'Chemicals', "keywords": ['fluorochem', 'gujarat fluorochemicals']},
    'FORCEMOT': {"name": 'Force Motors', "sector": 'Automobile', "keywords": ['force motors', 'forcemot']},
    'FORTIS': {"name": 'Fortis Healthcare', "sector": 'Pharma', "keywords": ['fortis', 'fortis healthcare']},
    'FSL': {"name": 'Firstsource Solutions', "sector": 'Services', "keywords": ['firstsource solutions', 'fsl']},
    'GABRIEL': {"name": 'Gabriel India', "sector": 'Automobile', "keywords": ['gabriel', 'gabriel india']},
    'GAIL': {"name": 'GAIL', "sector": 'Oil & Gas', "keywords": ['gail']},
    'GALLANTT': {"name": 'Gallantt Ispat', "sector": 'Capital Goods', "keywords": ['gallantt', 'gallantt ispat']},
    'GESHIP': {"name": 'Great Eastern Shipping', "sector": 'Services', "keywords": ['geship', 'great eastern shipping']},
    'GICRE': {"name": 'General Insurance of India', "sector": 'Insurance', "keywords": ['general insurance of india', 'gicre']},
    'GILLETTE': {"name": 'Gillette India', "sector": 'FMCG', "keywords": ['gillette', 'gillette india']},
    'GLAND': {"name": 'Gland Pharma', "sector": 'Pharma', "keywords": ['gland', 'gland pharma']},
    'GLAXO': {"name": 'Glaxosmithkline Pharmaceuticals', "sector": 'Pharma', "keywords": ['glaxo', 'glaxosmithkline pharmaceuticals']},
    'GLENMARK': {"name": 'Glenmark Pharmaceuticals', "sector": 'Pharma', "keywords": ['glenmark', 'glenmark pharmaceuticals']},
    'GMDCLTD': {"name": 'Gujarat Mineral Development', "sector": 'Metals', "keywords": ['gmdcltd', 'gujarat mineral development']},
    'GMRAIRPORT': {"name": 'GMR Airports', "sector": 'Services', "keywords": ['gmr airports', 'gmrairport']},
    'GODFRYPHLP': {"name": 'Godfrey Phillips India', "sector": 'FMCG', "keywords": ['godfrey phillips india', 'godfryphlp']},
    'GODIGIT': {"name": 'Go Digit General Insurance', "sector": 'Insurance', "keywords": ['go digit general insurance', 'godigit']},
    'GODREJCP': {"name": 'Godrej Consumer Products', "sector": 'FMCG', "keywords": ['godrej consumer products', 'godrejcp']},
    'GODREJIND': {"name": 'Godrej Industries', "sector": 'Diversified', "keywords": ['godrej industries', 'godrejind']},
    'GODREJPROP': {"name": 'Godrej Properties', "sector": 'Real Estate', "keywords": ['godrej properties', 'godrejprop']},
    'GPIL': {"name": 'Godawari Power & Ispat', "sector": 'Capital Goods', "keywords": ['godawari power & ispat', 'gpil']},
    'GRANULES': {"name": 'Granules India', "sector": 'Pharma', "keywords": ['granules', 'granules india']},
    'GRAPHITE': {"name": 'Graphite India', "sector": 'Capital Goods', "keywords": ['graphite', 'graphite india']},
    'GRASIM': {"name": 'Grasim Industries', "sector": 'Cement', "keywords": ['grasim', 'grasim industries']},
    'GRAVITA': {"name": 'Gravita India', "sector": 'Metals', "keywords": ['gravita', 'gravita india']},
    'GROWW': {"name": 'Billionbrains Garage Ventures', "sector": 'Financial Services', "keywords": ['billionbrains garage ventures', 'groww']},
    'GRSE': {"name": 'Garden Reach Shipbuilders & Engineers', "sector": 'Capital Goods', "keywords": ['garden reach shipbuilders & engineers', 'grse']},
    'GVT&D': {"name": 'GE Vernova T&D India', "sector": 'Capital Goods', "keywords": ['ge vernova t&d india', 'gvt&d']},
    'HAL': {"name": 'Hindustan Aeronautics', "sector": 'Capital Goods', "keywords": ['hal', 'hindustan aeronautics']},
    'HAVELLS': {"name": 'Havells India', "sector": 'Consumer Durables', "keywords": ['havells', 'havells india']},
    'HBLENGINE': {"name": 'HBL Engineering', "sector": 'Capital Goods', "keywords": ['hbl engineering', 'hblengine']},
    'HCLTECH': {"name": 'HCL Technologies', "sector": 'IT', "keywords": ['hcl technologies', 'hcltech']},
    'HDBFS': {"name": 'HDB Financial Services', "sector": 'NBFC', "keywords": ['hdb financial services', 'hdbfs']},
    'HDFCAMC': {"name": 'HDFC Asset Management', "sector": 'AMC/Wealth', "keywords": ['hdfc asset management', 'hdfcamc']},
    'HDFCBANK': {"name": 'HDFC Bank', "sector": 'Banking', "keywords": ['hdfc bank', 'hdfcbank']},
    'HDFCLIFE': {"name": 'HDFC Life Insurance', "sector": 'Insurance', "keywords": ['hdfc life insurance', 'hdfclife']},
    'HEG': {"name": 'H E G', "sector": 'Capital Goods', "keywords": ['h e g', 'heg']},
    'HEROMOTOCO': {"name": 'Hero MotoCorp', "sector": 'Automobile', "keywords": ['hero motocorp', 'heromotoco']},
    'HEXT': {"name": 'Hexaware Technologies', "sector": 'IT', "keywords": ['hexaware technologies', 'hext']},
    'HFCL': {"name": 'HFCL', "sector": 'Telecom', "keywords": ['hfcl']},
    'HINDALCO': {"name": 'Hindalco Industries', "sector": 'Metals', "keywords": ['hindalco', 'hindalco industries']},
    'HINDCOPPER': {"name": 'Hindustan Copper', "sector": 'Metals', "keywords": ['hindcopper', 'hindustan copper']},
    'HINDPETRO': {"name": 'Hindustan Petroleum', "sector": 'Oil & Gas', "keywords": ['hindpetro', 'hindustan petroleum']},
    'HINDUNILVR': {"name": 'Hindustan Unilever', "sector": 'FMCG', "keywords": ['hindunilvr', 'hindustan unilever']},
    'HINDZINC': {"name": 'Hindustan Zinc', "sector": 'Metals', "keywords": ['hindustan zinc', 'hindzinc']},
    'HOMEFIRST': {"name": 'Home First Finance India', "sector": 'NBFC', "keywords": ['home first finance india', 'homefirst']},
    'HONASA': {"name": 'Honasa Consumer', "sector": 'FMCG', "keywords": ['honasa', 'honasa consumer']},
    'HONAUT': {"name": 'Honeywell Automation India', "sector": 'Capital Goods', "keywords": ['honaut', 'honeywell automation india']},
    'HSCL': {"name": 'Himadri Speciality Chemical', "sector": 'Chemicals', "keywords": ['himadri speciality chemical', 'hscl']},
    'HUDCO': {"name": 'Housing & Urban Development', "sector": 'NBFC', "keywords": ['housing & urban development', 'hudco']},
    'HYUNDAI': {"name": 'Hyundai Motor India', "sector": 'Automobile', "keywords": ['hyundai', 'hyundai motor india']},
    'ICICIAMC': {"name": 'ICICI Prudential Asset Management', "sector": 'AMC/Wealth', "keywords": ['icici prudential asset management', 'iciciamc']},
    'ICICIBANK': {"name": 'ICICI Bank', "sector": 'Banking', "keywords": ['icici bank', 'icicibank']},
    'ICICIGI': {"name": 'ICICI Lombard General Insurance', "sector": 'Insurance', "keywords": ['icici lombard general insurance', 'icicigi']},
    'ICICIPRULI': {"name": 'ICICI Prudential Life Insurance', "sector": 'Insurance', "keywords": ['icici prudential life insurance', 'icicipruli']},
    'IDBI': {"name": 'IDBI Bank', "sector": 'Banking', "keywords": ['idbi', 'idbi bank']},
    'IDEA': {"name": 'Vodafone Idea', "sector": 'Telecom', "keywords": ['idea', 'vodafone idea']},
    'IDFCFIRSTB': {"name": 'IDFC First Bank', "sector": 'Banking', "keywords": ['idfc first bank', 'idfcfirstb']},
    'IEX': {"name": 'Indian Energy Exchange', "sector": 'NBFC', "keywords": ['iex', 'indian energy exchange']},
    'IFCI': {"name": 'IFCI', "sector": 'Financial Services', "keywords": ['ifci']},
    'IGIL': {"name": 'International Gemological Institute', "sector": 'Services', "keywords": ['igil', 'international gemological institute']},
    'IGL': {"name": 'Indraprastha Gas', "sector": 'Oil & Gas', "keywords": ['igl', 'indraprastha gas']},
    'IIFL': {"name": 'IIFL Finance', "sector": 'NBFC', "keywords": ['iifl', 'iifl finance']},
    'IKS': {"name": 'Inventurus Knowledge Solutions', "sector": 'IT', "keywords": ['iks', 'inventurus knowledge solutions']},
    'INDGN': {"name": 'Indegene', "sector": 'Pharma', "keywords": ['indegene', 'indgn']},
    'INDHOTEL': {"name": 'Indian Hotels', "sector": 'Consumer', "keywords": ['indhotel', 'indian hotels']},
    'INDIACEM': {"name": 'India Cements', "sector": 'Cement', "keywords": ['india cements', 'indiacem']},
    'INDIAMART': {"name": 'Indiamart Intermesh', "sector": 'Consumer', "keywords": ['indiamart', 'indiamart intermesh']},
    'INDIANB': {"name": 'Indian Bank', "sector": 'Banking', "keywords": ['indian bank', 'indianb']},
    'INDIGO': {"name": 'InterGlobe Aviation', "sector": 'Services', "keywords": ['indigo', 'interglobe aviation']},
    'INDUSINDBK': {"name": 'IndusInd Bank', "sector": 'Banking', "keywords": ['indusind bank', 'indusindbk']},
    'INDUSTOWER': {"name": 'Indus Towers', "sector": 'Telecom', "keywords": ['indus towers', 'industower']},
    'INFY': {"name": 'Infosys', "sector": 'IT', "keywords": ['infosys', 'infy']},
    'INOXWIND': {"name": 'Inox Wind', "sector": 'Capital Goods', "keywords": ['inox wind', 'inoxwind']},
    'INTELLECT': {"name": 'Intellect Design Arena', "sector": 'IT', "keywords": ['intellect', 'intellect design arena']},
    'IOB': {"name": 'Indian Overseas Bank', "sector": 'Banking', "keywords": ['indian overseas bank', 'iob']},
    'IOC': {"name": 'Indian Oil', "sector": 'Oil & Gas', "keywords": ['indian oil', 'ioc']},
    'IPCALAB': {"name": 'Ipca Laboratories', "sector": 'Pharma', "keywords": ['ipca laboratories', 'ipcalab']},
    'IRB': {"name": 'IRB Infrastructure Developers', "sector": 'Infrastructure', "keywords": ['irb', 'irb infrastructure developers']},
    'IRCON': {"name": 'IRCON International', "sector": 'Infrastructure', "keywords": ['ircon', 'ircon international']},
    'IRCTC': {"name": 'Indian Railway Catering And Tourism', "sector": 'Consumer', "keywords": ['indian railway catering and tourism', 'irctc']},
    'IREDA': {"name": 'Indian Renewable Energy Development Agency', "sector": 'Financial Services', "keywords": ['indian renewable energy development agency', 'ireda']},
    'IRFC': {"name": 'Indian Railway Finance', "sector": 'NBFC', "keywords": ['indian railway finance', 'irfc']},
    'ITC': {"name": 'ITC', "sector": 'FMCG', "keywords": ['itc']},
    'ITCHOTELS': {"name": 'ITC Hotels', "sector": 'Consumer', "keywords": ['itc hotels', 'itchotels']},
    'ITI': {"name": 'ITI', "sector": 'Telecom', "keywords": ['iti']},
    'J&KBANK': {"name": 'Jammu & Kashmir Bank', "sector": 'Banking', "keywords": ['j&kbank', 'jammu & kashmir bank']},
    'JAINREC': {"name": 'Jain Resource Recycling', "sector": 'Metals', "keywords": ['jain resource recycling', 'jainrec']},
    'JBCHEPHARM': {"name": 'J B Chemicals & Pharmaceuticals', "sector": 'Pharma', "keywords": ['j b chemicals & pharmaceuticals', 'jbchepharm']},
    'JBMA': {"name": 'JBM Auto', "sector": 'Automobile', "keywords": ['jbm auto', 'jbma']},
    'JINDALSAW': {"name": 'Jindal Saw', "sector": 'Capital Goods', "keywords": ['jindal saw', 'jindalsaw']},
    'JINDALSTEL': {"name": 'Jindal Steel', "sector": 'Metals', "keywords": ['jindal steel', 'jindalstel']},
    'JIOFIN': {"name": 'Jio Financial Services', "sector": 'NBFC', "keywords": ['jio financial services', 'jiofin']},
    'JKCEMENT': {"name": 'J K Cement', "sector": 'Cement', "keywords": ['j k cement', 'jkcement']},
    'JKTYRE': {"name": 'JK Tyre & Industries', "sector": 'Automobile', "keywords": ['jk tyre & industries', 'jktyre']},
    'JMFINANCIL': {"name": 'JM Financial', "sector": 'NBFC', "keywords": ['jm financial', 'jmfinancil']},
    'JPPOWER': {"name": 'Jaiprakash Power Ventures', "sector": 'Power', "keywords": ['jaiprakash power ventures', 'jppower']},
    'JSL': {"name": 'Jindal Stainless', "sector": 'Metals', "keywords": ['jindal stainless', 'jsl']},
    'JSWCEMENT': {"name": 'JSW Cement', "sector": 'Cement', "keywords": ['jsw cement', 'jswcement']},
    'JSWDULUX': {"name": 'JSW Dulux', "sector": 'Consumer Durables', "keywords": ['jsw dulux', 'jswdulux']},
    'JSWENERGY': {"name": 'JSW Energy', "sector": 'Power', "keywords": ['jsw energy', 'jswenergy']},
    'JSWINFRA': {"name": 'JSW Infrastructure', "sector": 'Services', "keywords": ['jsw infrastructure', 'jswinfra']},
    'JSWSTEEL': {"name": 'JSW Steel', "sector": 'Metals', "keywords": ['jsw steel', 'jswsteel']},
    'JUBLFOOD': {"name": 'Jubilant Foodworks', "sector": 'Consumer', "keywords": ['jubilant foodworks', 'jublfood']},
    'JUBLINGREA': {"name": 'Jubilant Ingrevia', "sector": 'Chemicals', "keywords": ['jubilant ingrevia', 'jublingrea']},
    'JUBLPHARMA': {"name": 'Jubilant Pharmova', "sector": 'Pharma', "keywords": ['jubilant pharmova', 'jublpharma']},
    'JWL': {"name": 'Jupiter Wagons', "sector": 'Capital Goods', "keywords": ['jupiter wagons', 'jwl']},
    'JYOTICNC': {"name": 'Jyoti CNC Automation', "sector": 'Capital Goods', "keywords": ['jyoti cnc automation', 'jyoticnc']},
    'KAJARIACER': {"name": 'Kajaria Ceramics', "sector": 'Consumer Durables', "keywords": ['kajaria ceramics', 'kajariacer']},
    'KALYANKJIL': {"name": 'Kalyan Jewellers India', "sector": 'Consumer Durables', "keywords": ['kalyan jewellers india', 'kalyankjil']},
    'KARURVYSYA': {"name": 'Karur Vysya Bank', "sector": 'Banking', "keywords": ['karur vysya bank', 'karurvysya']},
    'KAYNES': {"name": 'Kaynes Technology India', "sector": 'Capital Goods', "keywords": ['kaynes', 'kaynes technology india']},
    'KEC': {"name": 'Kec International', "sector": 'Infrastructure', "keywords": ['kec', 'kec international']},
    'KEI': {"name": 'KEI Industries', "sector": 'Capital Goods', "keywords": ['kei', 'kei industries']},
    'KFINTECH': {"name": 'Kfin Technologies', "sector": 'Financial Services', "keywords": ['kfin technologies', 'kfintech']},
    'KIMS': {"name": 'Krishna Institute of Medical Sciences', "sector": 'Pharma', "keywords": ['kims', 'krishna institute of medical sciences']},
    'KIRLOSENG': {"name": 'Kirloskar Oil Eng', "sector": 'Capital Goods', "keywords": ['kirloseng', 'kirloskar oil eng']},
    'KOTAKBANK': {"name": 'Kotak Mahindra Bank', "sector": 'Banking', "keywords": ['kotak mahindra bank', 'kotakbank']},
    'KPIL': {"name": 'Kalpataru Projects International', "sector": 'Infrastructure', "keywords": ['kalpataru projects international', 'kpil']},
    'KPITTECH': {"name": 'KPIT Technologies', "sector": 'IT', "keywords": ['kpit technologies', 'kpittech']},
    'KPRMILL': {"name": 'K P R Mill', "sector": 'Textiles', "keywords": ['k p r mill', 'kprmill']},
    'LALPATHLAB': {"name": 'Dr Lal Path Labs', "sector": 'Pharma', "keywords": ['dr lal path labs', 'lalpathlab']},
    'LATENTVIEW': {"name": 'Latent View Analytics', "sector": 'IT', "keywords": ['latent view analytics', 'latentview']},
    'LAURUSLABS': {"name": 'Laurus Labs', "sector": 'Pharma', "keywords": ['laurus labs', 'lauruslabs']},
    'LEMONTREE': {"name": 'Lemon Tree Hotels', "sector": 'Consumer', "keywords": ['lemon tree hotels', 'lemontree']},
    'LENSKART': {"name": 'Lenskart Solutions', "sector": 'Consumer', "keywords": ['lenskart', 'lenskart solutions']},
    'LGEINDIA': {"name": 'LG Electronics India', "sector": 'Consumer Durables', "keywords": ['lg electronics india', 'lgeindia']},
    'LICHSGFIN': {"name": 'LIC Housing Finance', "sector": 'NBFC', "keywords": ['lic housing finance', 'lichsgfin']},
    'LICI': {"name": 'Life Insurance of India', "sector": 'Insurance', "keywords": ['lici', 'life insurance of india']},
    'LINDEINDIA': {"name": 'Linde India', "sector": 'Chemicals', "keywords": ['linde india', 'lindeindia']},
    'LLOYDSME': {"name": 'Lloyds Metals And Energy', "sector": 'Metals', "keywords": ['lloyds metals and energy', 'lloydsme']},
    'LODHA': {"name": 'Lodha Developers', "sector": 'Real Estate', "keywords": ['lodha', 'lodha developers']},
    'LT': {"name": 'Larsen & Toubro', "sector": 'Infrastructure', "keywords": ['larsen & toubro', 'lt']},
    'LTF': {"name": 'L&T Finance', "sector": 'NBFC', "keywords": ['l&t finance', 'ltf']},
    'LTFOODS': {"name": 'LT Foods', "sector": 'FMCG', "keywords": ['lt foods', 'ltfoods']},
    'LTM': {"name": 'LTM', "sector": 'IT', "keywords": ['ltm']},
    'LTTS': {"name": 'L&T Technology Services', "sector": 'IT', "keywords": ['l&t technology services', 'ltts']},
    'LUPIN': {"name": 'Lupin', "sector": 'Pharma', "keywords": ['lupin']},
    'M&M': {"name": 'Mahindra & Mahindra', "sector": 'Automobile', "keywords": ['m&m', 'mahindra & mahindra']},
    'M&MFIN': {"name": 'Mahindra & Mahindra Financial Services', "sector": 'NBFC', "keywords": ['m&mfin', 'mahindra & mahindra financial services']},
    'MAHABANK': {"name": 'Bank of Maharashtra', "sector": 'Banking', "keywords": ['bank of maharashtra', 'mahabank']},
    'MANAPPURAM': {"name": 'Manappuram Finance', "sector": 'NBFC', "keywords": ['manappuram', 'manappuram finance']},
    'MANKIND': {"name": 'Mankind Pharma', "sector": 'Pharma', "keywords": ['mankind', 'mankind pharma']},
    'MAPMYINDIA': {"name": 'C E Info Systems', "sector": 'IT', "keywords": ['c e info systems', 'mapmyindia']},
    'MARICO': {"name": 'Marico', "sector": 'FMCG', "keywords": ['marico']},
    'MARUTI': {"name": 'Maruti Suzuki India', "sector": 'Automobile', "keywords": ['maruti', 'maruti suzuki india']},
    'MAXHEALTH': {"name": 'Max Healthcare Institute', "sector": 'Pharma', "keywords": ['max healthcare institute', 'maxhealth']},
    'MAZDOCK': {"name": 'Mazagoan Dock Shipbuilders', "sector": 'Capital Goods', "keywords": ['mazagoan dock shipbuilders', 'mazdock']},
    'MCX': {"name": 'Multi Commodity Exchange of India', "sector": 'NBFC', "keywords": ['mcx', 'multi commodity exchange of india']},
    'MEDANTA': {"name": 'Global Health', "sector": 'Pharma', "keywords": ['global health', 'medanta']},
    'MEESHO': {"name": 'Meesho', "sector": 'Consumer', "keywords": ['meesho']},
    'MFSL': {"name": 'Max Financial Services', "sector": 'NBFC', "keywords": ['max financial services', 'mfsl']},
    'MGL': {"name": 'Mahanagar Gas', "sector": 'Oil & Gas', "keywords": ['mahanagar gas', 'mgl']},
    'MINDACORP': {"name": 'Minda', "sector": 'Automobile', "keywords": ['minda', 'mindacorp']},
    'MMTC': {"name": 'MMTC', "sector": 'Services', "keywords": ['mmtc']},
    'MOTHERSON': {"name": 'Samvardhana Motherson International', "sector": 'Automobile', "keywords": ['motherson', 'samvardhana motherson international']},
    'MOTILALOFS': {"name": 'Motilal Oswal Financial Services', "sector": 'NBFC', "keywords": ['motilal oswal financial services', 'motilalofs']},
    'MPHASIS': {"name": 'MphasiS', "sector": 'IT', "keywords": ['mphasis']},
    'MRF': {"name": 'MRF', "sector": 'Automobile', "keywords": ['mrf']},
    'MRPL': {"name": 'Mangalore Refinery & Petrochemicals', "sector": 'Oil & Gas', "keywords": ['mangalore refinery & petrochemicals', 'mrpl']},
    'MSUMI': {"name": 'Motherson Sumi Wiring India', "sector": 'Automobile', "keywords": ['motherson sumi wiring india', 'msumi']},
    'MUTHOOTFIN': {"name": 'Muthoot Finance', "sector": 'NBFC', "keywords": ['muthoot finance', 'muthootfin']},
    'NAM-INDIA': {"name": 'Nippon Life India Asset Management', "sector": 'Insurance', "keywords": ['nam-india', 'nippon life india asset management']},
    'NATCOPHARM': {"name": 'NATCO Pharma', "sector": 'Pharma', "keywords": ['natco pharma', 'natcopharm']},
    'NATIONALUM': {"name": 'National Aluminium', "sector": 'Metals', "keywords": ['national aluminium', 'nationalum']},
    'NAUKRI': {"name": 'Info Edge', "sector": 'Consumer', "keywords": ['info edge', 'naukri']},
    'NAVA': {"name": 'Nava', "sector": 'Power', "keywords": ['nava']},
    'NAVINFLUOR': {"name": 'Navin Fluorine International', "sector": 'Chemicals', "keywords": ['navin fluorine international', 'navinfluor']},
    'NBCC': {"name": 'NBCC', "sector": 'Infrastructure', "keywords": ['nbcc']},
    'NCC': {"name": 'NCC', "sector": 'Infrastructure', "keywords": ['ncc']},
    'NESTLEIND': {"name": 'Nestle India', "sector": 'FMCG', "keywords": ['nestle india', 'nestleind']},
    'NETWEB': {"name": 'Netweb Technologies India', "sector": 'IT', "keywords": ['netweb', 'netweb technologies india']},
    'NEULANDLAB': {"name": 'Neuland Laboratories', "sector": 'Pharma', "keywords": ['neuland laboratories', 'neulandlab']},
    'NEWGEN': {"name": 'Newgen Software Technologies', "sector": 'IT', "keywords": ['newgen', 'newgen software technologies']},
    'NH': {"name": 'Narayana Hrudayalaya', "sector": 'Pharma', "keywords": ['narayana hrudayalaya', 'nh']},
    'NHPC': {"name": 'NHPC', "sector": 'Power', "keywords": ['nhpc']},
    'NIACL': {"name": 'The New India Assurance', "sector": 'Insurance', "keywords": ['niacl', 'the new india assurance']},
    'NIVABUPA': {"name": 'Niva Bupa Health Insurance', "sector": 'Insurance', "keywords": ['niva bupa health insurance', 'nivabupa']},
    'NLCINDIA': {"name": 'NLC India', "sector": 'Power', "keywords": ['nlc india', 'nlcindia']},
    'NMDC': {"name": 'NMDC', "sector": 'Metals', "keywords": ['nmdc']},
    'NSLNISP': {"name": 'NMDC Steel', "sector": 'Metals', "keywords": ['nmdc steel', 'nslnisp']},
    'NTPC': {"name": 'NTPC', "sector": 'Power', "keywords": ['ntpc']},
    'NTPCGREEN': {"name": 'NTPC Green Energy', "sector": 'Power', "keywords": ['ntpc green energy', 'ntpcgreen']},
    'NUVAMA': {"name": 'Nuvama Wealth Management', "sector": 'AMC/Wealth', "keywords": ['nuvama', 'nuvama wealth management']},
    'NUVOCO': {"name": 'Nuvoco Vistas', "sector": 'Cement', "keywords": ['nuvoco', 'nuvoco vistas']},
    'NYKAA': {"name": 'FSN E-Commerce Ventures', "sector": 'Consumer', "keywords": ['fsn e-commerce ventures', 'nykaa']},
    'OBEROIRLTY': {"name": 'Oberoi Realty', "sector": 'Real Estate', "keywords": ['oberoi realty', 'oberoirlty']},
    'OFSS': {"name": 'Oracle Financial Services Software', "sector": 'IT', "keywords": ['ofss', 'oracle financial services software']},
    'OIL': {"name": 'Oil India', "sector": 'Oil & Gas', "keywords": ['oil', 'oil india']},
    'OLAELEC': {"name": 'Ola Electric Mobility', "sector": 'Automobile', "keywords": ['ola electric mobility', 'olaelec']},
    'OLECTRA': {"name": 'Olectra Greentech', "sector": 'Automobile', "keywords": ['olectra', 'olectra greentech']},
    'ONESOURCE': {"name": 'Onesource Specialty Pharma', "sector": 'Pharma', "keywords": ['onesource', 'onesource specialty pharma']},
    'ONGC': {"name": 'Oil & Natural Gas', "sector": 'Oil & Gas', "keywords": ['oil & natural gas', 'ongc']},
    'PAGEIND': {"name": 'Page Industries', "sector": 'Textiles', "keywords": ['page industries', 'pageind']},
    'PARADEEP': {"name": 'Paradeep Phosphates', "sector": 'Chemicals', "keywords": ['paradeep', 'paradeep phosphates']},
    'PATANJALI': {"name": 'Patanjali Foods', "sector": 'FMCG', "keywords": ['patanjali', 'patanjali foods']},
    'PAYTM': {"name": 'One 97 Communications', "sector": 'Financial Services', "keywords": ['one 97 communications', 'paytm']},
    'PCBL': {"name": 'PCBL Chemical', "sector": 'Chemicals', "keywords": ['pcbl', 'pcbl chemical']},
    'PERSISTENT': {"name": 'Persistent Systems', "sector": 'IT', "keywords": ['persistent', 'persistent systems']},
    'PETRONET': {"name": 'Petronet LNG', "sector": 'Oil & Gas', "keywords": ['petronet', 'petronet lng']},
    'PFC': {"name": 'Power Finance', "sector": 'NBFC', "keywords": ['pfc', 'power finance']},
    'PFIZER': {"name": 'Pfizer', "sector": 'Pharma', "keywords": ['pfizer']},
    'PGEL': {"name": 'PG Electroplast', "sector": 'Consumer Durables', "keywords": ['pg electroplast', 'pgel']},
    'PHOENIXLTD': {"name": 'Phoenix Mills', "sector": 'Real Estate', "keywords": ['phoenix mills', 'phoenixltd']},
    'PIDILITIND': {"name": 'Pidilite Industries', "sector": 'Chemicals', "keywords": ['pidilite industries', 'pidilitind']},
    'PIIND': {"name": 'PI Industries', "sector": 'Chemicals', "keywords": ['pi industries', 'piind']},
    'PINELABS': {"name": 'Pine Labs', "sector": 'Financial Services', "keywords": ['pine labs', 'pinelabs']},
    'PIRAMALFIN': {"name": 'Piramal Finance', "sector": 'NBFC', "keywords": ['piramal finance', 'piramalfin']},
    'PNB': {"name": 'Punjab National Bank', "sector": 'Banking', "keywords": ['pnb', 'punjab national bank']},
    'PNBHOUSING': {"name": 'PNB Housing Finance', "sector": 'NBFC', "keywords": ['pnb housing finance', 'pnbhousing']},
    'POLICYBZR': {"name": 'PB Fintech', "sector": 'NBFC', "keywords": ['pb fintech', 'policybzr']},
    'POLYCAB': {"name": 'Polycab India', "sector": 'Capital Goods', "keywords": ['polycab', 'polycab india']},
    'POLYMED': {"name": 'Poly Medicure', "sector": 'Pharma', "keywords": ['poly medicure', 'polymed']},
    'POONAWALLA': {"name": 'Poonawalla Fincorp', "sector": 'NBFC', "keywords": ['poonawalla', 'poonawalla fincorp']},
    'POWERGRID': {"name": 'Power Grid of India', "sector": 'Power', "keywords": ['power grid of india', 'powergrid']},
    'POWERINDIA': {"name": 'Hitachi Energy India', "sector": 'Capital Goods', "keywords": ['hitachi energy india', 'powerindia']},
    'PPLPHARMA': {"name": 'Piramal Pharma', "sector": 'Pharma', "keywords": ['piramal pharma', 'pplpharma']},
    'PREMIERENE': {"name": 'Premier Energies', "sector": 'Capital Goods', "keywords": ['premier energies', 'premierene']},
    'PRESTIGE': {"name": 'Prestige Estates Projects', "sector": 'Real Estate', "keywords": ['prestige', 'prestige estates projects']},
    'PTCIL': {"name": 'PTC Industries', "sector": 'Capital Goods', "keywords": ['ptc industries', 'ptcil']},
    'PVRINOX': {"name": 'PVR INOX', "sector": 'Media', "keywords": ['pvr inox', 'pvrinox']},
    'PWL': {"name": 'Physicswallah', "sector": 'Consumer', "keywords": ['physicswallah', 'pwl']},
    'RADICO': {"name": 'Radico Khaitan', "sector": 'FMCG', "keywords": ['radico', 'radico khaitan']},
    'RAILTEL': {"name": 'Railtel Of India', "sector": 'Telecom', "keywords": ['railtel', 'railtel of india']},
    'RAINBOW': {"name": 'Rainbow Childrens Medicare', "sector": 'Pharma', "keywords": ['rainbow', 'rainbow childrens medicare']},
    'RAMCOCEM': {"name": 'The Ramco Cements', "sector": 'Cement', "keywords": ['ramcocem', 'the ramco cements']},
    'RBLBANK': {"name": 'RBL Bank', "sector": 'Banking', "keywords": ['rbl bank', 'rblbank']},
    'RECLTD': {"name": 'REC', "sector": 'Financial Services', "keywords": ['recltd']},
    'REDINGTON': {"name": 'Redington', "sector": 'Services', "keywords": ['redington']},
    'RELIANCE': {"name": 'Reliance Industries', "sector": 'Oil & Gas', "keywords": ['reliance', 'reliance industries']},
    'RHIM': {"name": 'RHI MAGNESITA INDIA', "sector": 'Capital Goods', "keywords": ['rhi magnesita india', 'rhim']},
    'RITES': {"name": 'RITES', "sector": 'Infrastructure', "keywords": ['rites']},
    'RKFORGE': {"name": 'Ramkrishna Forgings', "sector": 'Automobile', "keywords": ['ramkrishna forgings', 'rkforge']},
    'RPOWER': {"name": 'Reliance Power', "sector": 'Power', "keywords": ['reliance power', 'rpower']},
    'RRKABEL': {"name": 'R R Kabel', "sector": 'Capital Goods', "keywords": ['r r kabel', 'rrkabel']},
    'RVNL': {"name": 'Rail Vikas Nigam', "sector": 'Infrastructure', "keywords": ['rail vikas nigam', 'rvnl']},
    'SAGILITY': {"name": 'Sagility', "sector": 'IT', "keywords": ['sagility']},
    'SAIL': {"name": 'Steel Authority of India', "sector": 'Metals', "keywords": ['sail', 'steel authority of india']},
    'SAILIFE': {"name": 'Sai Life Sciences', "sector": 'Pharma', "keywords": ['sai life sciences', 'sailife']},
    'SAMMAANCAP': {"name": 'Sammaan Capital', "sector": 'NBFC', "keywords": ['sammaan capital', 'sammaancap']},
    'SAPPHIRE': {"name": 'Sapphire Foods India', "sector": 'Consumer', "keywords": ['sapphire', 'sapphire foods india']},
    'SARDAEN': {"name": 'Sarda Energy and Minerals', "sector": 'Metals', "keywords": ['sarda energy and minerals', 'sardaen']},
    'SAREGAMA': {"name": 'Saregama India', "sector": 'Media', "keywords": ['saregama', 'saregama india']},
    'SBFC': {"name": 'SBFC Finance', "sector": 'NBFC', "keywords": ['sbfc', 'sbfc finance']},
    'SBICARD': {"name": 'SBI Cards and Payment Services', "sector": 'Financial Services', "keywords": ['sbi cards and payment services', 'sbicard']},
    'SBILIFE': {"name": 'SBI Life Insurance', "sector": 'Insurance', "keywords": ['sbi life insurance', 'sbilife']},
    'SBIN': {"name": 'State Bank of India', "sector": 'Banking', "keywords": ['sbin', 'state bank of india']},
    'SCHAEFFLER': {"name": 'Schaeffler India', "sector": 'Automobile', "keywords": ['schaeffler', 'schaeffler india']},
    'SCHNEIDER': {"name": 'Schneider Electric Infrastructure', "sector": 'Capital Goods', "keywords": ['schneider', 'schneider electric infrastructure']},
    'SCI': {"name": 'Shipping of India', "sector": 'Services', "keywords": ['sci', 'shipping of india']},
    'SHREECEM': {"name": 'Shree Cement', "sector": 'Cement', "keywords": ['shree cement', 'shreecem']},
    'SHRIRAMFIN': {"name": 'Shriram Finance', "sector": 'NBFC', "keywords": ['shriram finance', 'shriramfin']},
    'SHYAMMETL': {"name": 'Shyam Metalics and Energy', "sector": 'Capital Goods', "keywords": ['shyam metalics and energy', 'shyammetl']},
    'SIEMENS': {"name": 'Siemens', "sector": 'Capital Goods', "keywords": ['siemens']},
    'SIGNATURE': {"name": 'Signatureglobal', "sector": 'Real Estate', "keywords": ['signature', 'signatureglobal']},
    'SJVN': {"name": 'SJVN', "sector": 'Power', "keywords": ['sjvn']},
    'SOBHA': {"name": 'Sobha', "sector": 'Real Estate', "keywords": ['sobha']},
    'SOLARINDS': {"name": 'Solar Industries India', "sector": 'Chemicals', "keywords": ['solar industries india', 'solarinds']},
    'SONACOMS': {"name": 'Sona BLW Precision Forgings', "sector": 'Automobile', "keywords": ['sona blw precision forgings', 'sonacoms']},
    'SONATSOFTW': {"name": 'Sonata Software', "sector": 'IT', "keywords": ['sonata software', 'sonatsoftw']},
    'SPLPETRO': {"name": 'Supreme Petrochem', "sector": 'Chemicals', "keywords": ['splpetro', 'supreme petrochem']},
    'SRF': {"name": 'SRF', "sector": 'Chemicals', "keywords": ['srf']},
    'STARHEALTH': {"name": 'Star Health and Allied Insurance', "sector": 'Insurance', "keywords": ['star health and allied insurance', 'starhealth']},
    'SUMICHEM': {"name": 'Sumitomo Chemical India', "sector": 'Chemicals', "keywords": ['sumichem', 'sumitomo chemical india']},
    'SUNDARMFIN': {"name": 'Sundaram Finance', "sector": 'NBFC', "keywords": ['sundaram finance', 'sundarmfin']},
    'SUNPHARMA': {"name": 'Sun Pharmaceutical Industries', "sector": 'Pharma', "keywords": ['sun pharmaceutical industries', 'sunpharma']},
    'SUNTV': {"name": 'Sun TV Network', "sector": 'Media', "keywords": ['sun tv network', 'suntv']},
    'SUPREMEIND': {"name": 'Supreme Industries', "sector": 'Capital Goods', "keywords": ['supreme industries', 'supremeind']},
    'SUZLON': {"name": 'Suzlon Energy', "sector": 'Capital Goods', "keywords": ['suzlon', 'suzlon energy']},
    'SWANCORP': {"name": 'Swan', "sector": 'Chemicals', "keywords": ['swan', 'swancorp']},
    'SWIGGY': {"name": 'Swiggy', "sector": 'Consumer', "keywords": ['swiggy']},
    'SYNGENE': {"name": 'Syngene International', "sector": 'Pharma', "keywords": ['syngene', 'syngene international']},
    'SYRMA': {"name": 'Syrma SGS Technology', "sector": 'Capital Goods', "keywords": ['syrma', 'syrma sgs technology']},
    'TARIL': {"name": 'Transformers And Rectifiers', "sector": 'Capital Goods', "keywords": ['taril', 'transformers and rectifiers']},
    'TATACAP': {"name": 'Tata Capital', "sector": 'NBFC', "keywords": ['tata capital', 'tatacap']},
    'TATACHEM': {"name": 'Tata Chemicals', "sector": 'Chemicals', "keywords": ['tata chemicals', 'tatachem']},
    'TATACOMM': {"name": 'Tata Communications', "sector": 'Telecom', "keywords": ['tata communications', 'tatacomm']},
    'TATACONSUM': {"name": 'Tata Consumer Products', "sector": 'FMCG', "keywords": ['tata consumer products', 'tataconsum']},
    'TATAELXSI': {"name": 'Tata Elxsi', "sector": 'IT', "keywords": ['tata elxsi', 'tataelxsi']},
    'TATAINVEST': {"name": 'Tata Investment', "sector": 'NBFC', "keywords": ['tata investment', 'tatainvest']},
    'TATAPOWER': {"name": 'Tata Power', "sector": 'Power', "keywords": ['tata power', 'tatapower']},
    'TATASTEEL': {"name": 'Tata Steel', "sector": 'Metals', "keywords": ['tata steel', 'tatasteel']},
    'TATATECH': {"name": 'Tata Technologies', "sector": 'IT', "keywords": ['tata technologies', 'tatatech']},
    'TBOTEK': {"name": 'TBO Tek', "sector": 'Consumer', "keywords": ['tbo tek', 'tbotek']},
    'TCS': {"name": 'Tata Consultancy Services', "sector": 'IT', "keywords": ['tata consultancy services', 'tcs']},
    'TECHM': {"name": 'Tech Mahindra', "sector": 'IT', "keywords": ['tech mahindra', 'techm']},
    'TECHNOE': {"name": 'Techno Electric & Engineering', "sector": 'Infrastructure', "keywords": ['techno electric & engineering', 'technoe']},
    'TEGA': {"name": 'Tega Industries', "sector": 'Capital Goods', "keywords": ['tega', 'tega industries']},
    'TEJASNET': {"name": 'Tejas Networks', "sector": 'Telecom', "keywords": ['tejas networks', 'tejasnet']},
    'TENNIND': {"name": 'Tenneco Clean Air India', "sector": 'Automobile', "keywords": ['tenneco clean air india', 'tennind']},
    'THELEELA': {"name": 'Leela Palaces Hotels & Resorts', "sector": 'Consumer', "keywords": ['leela palaces hotels & resorts', 'theleela']},
    'THERMAX': {"name": 'Thermax', "sector": 'Capital Goods', "keywords": ['thermax']},
    'TIINDIA': {"name": 'Tube Investments of India', "sector": 'Automobile', "keywords": ['tiindia', 'tube investments of india']},
    'TIMKEN': {"name": 'Timken India', "sector": 'Capital Goods', "keywords": ['timken', 'timken india']},
    'TITAGARH': {"name": 'Titagarh Rail Systems', "sector": 'Capital Goods', "keywords": ['titagarh', 'titagarh rail systems']},
    'TITAN': {"name": 'Titan', "sector": 'Consumer Durables', "keywords": ['titan']},
    'TMCV': {"name": 'Tata Motors', "sector": 'Capital Goods', "keywords": ['tata motors', 'tmcv']},
    'TMPV': {"name": 'Tata Motors Passenger Vehicles', "sector": 'Automobile', "keywords": ['tata motors passenger vehicles', 'tmpv']},
    'TORNTPHARM': {"name": 'Torrent Pharmaceuticals', "sector": 'Pharma', "keywords": ['torntpharm', 'torrent pharmaceuticals']},
    'TORNTPOWER': {"name": 'Torrent Power', "sector": 'Power', "keywords": ['torntpower', 'torrent power']},
    'TRAVELFOOD': {"name": 'Travel Food Services', "sector": 'Consumer', "keywords": ['travel food services', 'travelfood']},
    'TRENT': {"name": 'Trent', "sector": 'Consumer', "keywords": ['trent']},
    'TRIDENT': {"name": 'Trident', "sector": 'Textiles', "keywords": ['trident']},
    'TRITURBINE': {"name": 'Triveni Turbine', "sector": 'Capital Goods', "keywords": ['triturbine', 'triveni turbine']},
    'TTML': {"name": 'Tata Teleservices (Maharashtra)', "sector": 'Telecom', "keywords": ['tata teleservices (maharashtra)', 'ttml']},
    'TVSMOTOR': {"name": 'TVS Motor', "sector": 'Automobile', "keywords": ['tvs motor', 'tvsmotor']},
    'UBL': {"name": 'United Breweries', "sector": 'FMCG', "keywords": ['ubl', 'united breweries']},
    'UCOBANK': {"name": 'UCO Bank', "sector": 'Banking', "keywords": ['uco bank', 'ucobank']},
    'ULTRACEMCO': {"name": 'UltraTech Cement', "sector": 'Cement', "keywords": ['ultracemco', 'ultratech cement']},
    'UNIONBANK': {"name": 'Union Bank of India', "sector": 'Banking', "keywords": ['union bank of india', 'unionbank']},
    'UNITDSPR': {"name": 'United Spirits', "sector": 'FMCG', "keywords": ['unitdspr', 'united spirits']},
    'UNOMINDA': {"name": 'UNO Minda', "sector": 'Automobile', "keywords": ['uno minda', 'unominda']},
    'UPL': {"name": 'UPL', "sector": 'Chemicals', "keywords": ['upl']},
    'URBANCO': {"name": 'Urban', "sector": 'Consumer', "keywords": ['urban', 'urbanco']},
    'USHAMART': {"name": 'Usha Martin', "sector": 'Capital Goods', "keywords": ['usha martin', 'ushamart']},
    'UTIAMC': {"name": 'UTI Asset Management', "sector": 'AMC/Wealth', "keywords": ['uti asset management', 'utiamc']},
    'VBL': {"name": 'Varun Beverages', "sector": 'FMCG', "keywords": ['varun beverages', 'vbl']},
    'VEDL': {"name": 'Vedanta', "sector": 'Metals', "keywords": ['vedanta', 'vedl']},
    'VIJAYA': {"name": 'Vijaya Diagnostic Centre', "sector": 'Pharma', "keywords": ['vijaya', 'vijaya diagnostic centre']},
    'VMM': {"name": 'Vishal Mega Mart', "sector": 'Consumer', "keywords": ['vishal mega mart', 'vmm']},
    'VOLTAS': {"name": 'Voltas', "sector": 'Consumer Durables', "keywords": ['voltas']},
    'VTL': {"name": 'Vardhman Textiles', "sector": 'Textiles', "keywords": ['vardhman textiles', 'vtl']},
    'WAAREEENER': {"name": 'Waaree Energies', "sector": 'Capital Goods', "keywords": ['waaree energies', 'waareeener']},
    'WELCORP': {"name": 'Welspun', "sector": 'Capital Goods', "keywords": ['welcorp', 'welspun']},
    'WELSPUNLIV': {"name": 'Welspun Living', "sector": 'Textiles', "keywords": ['welspun living', 'welspunliv']},
    'WHIRLPOOL': {"name": 'Whirlpool of India', "sector": 'Consumer Durables', "keywords": ['whirlpool', 'whirlpool of india']},
    'WIPRO': {"name": 'Wipro', "sector": 'IT', "keywords": ['wipro']},
    'WOCKPHARMA': {"name": 'Wockhardt', "sector": 'Pharma', "keywords": ['wockhardt', 'wockpharma']},
    'YESBANK': {"name": 'Yes Bank', "sector": 'Banking', "keywords": ['yes bank', 'yesbank']},
    'ZEEL': {"name": 'Zee Entertainment Enterprises', "sector": 'Media', "keywords": ['zee entertainment enterprises', 'zeel']},
    'ZENSARTECH': {"name": 'Zensar Technolgies', "sector": 'IT', "keywords": ['zensar technolgies', 'zensartech']},
    'ZENTEC': {"name": 'Zen Technologies', "sector": 'Capital Goods', "keywords": ['zen technologies', 'zentec']},
    'ZFCVINDIA': {"name": 'ZF Commercial Vehicle Control Systems India', "sector": 'Automobile', "keywords": ['zf commercial vehicle control systems india', 'zfcvindia']},
    'ZYDUSLIFE': {"name": 'Zydus Lifesciences', "sector": 'Pharma', "keywords": ['zydus lifesciences', 'zyduslife']},
    'ZYDUSWELL': {"name": 'Zydus Wellness', "sector": 'FMCG', "keywords": ['zydus wellness', 'zyduswell']},
}
